### ISSUE TITLE
Number 1 recruiting class

### ISSUE THREAD

**Issue by daiyveal** [akeaswaran/cfc-bugs#1]
**Describe the bug**
Every time I get the number 1 recruiting class it skips the year. I got the number 1 class in 2021 and 2024 and at the end of recruitment it skipped to 2022 and 2025

**To Reproduce**
To reproduce just get the number 1 class.

**iOS version**: iOS 13.4
**CFC version**: Version 4.0.1
**iOS device**: iPhone 11 Pro Max
**Jailbroken**: not jail broken
**Reproducible:** Happens every time I get the number 1 class

**Expected behavior**

**Screenshots**
![DDA7EB8E-D3F2-4CE4-A1C9-15FC5F035B66](https://user-images.githubusercontent.com/58782274/78845011-a78fee00-79c4-11ea-8ae1-7ebc131c5471.png)

**Video**

**Additional context**

**Comment by akeaswaran** [comment]
Thank you for filling out the report template. Will take a deeper look into this and try to reproduce.

**Comment by akeaswaran** [comment]
Think I solved this, should be fixed in 4.0.2 -- thanks for reporting!
