### ISSUE TITLE
Coach Score

### ISSUE THREAD

**Issue by Dubs8876** [akeaswaran/cfc-bugs#10]
I have looked all over the app but cannot figure out how the Coach’s Score is measured. I won the national championship several seasons in a row and it was high. I ended up with a higher ranked offense and defense and did everything the same way and my coaches score was a third of what it was my first ten seasons. ??????  I would appreciate if someone would explain what is measured to reach the coach’s score.

**Comment by akeaswaran** [comment]
Here's the formula in code:

```
int prestigeDiff = [self.team calculatePrestigeChange];
return (prestigeDiff * 7) + (self.team.teamStrengthOfWins / 20) + (3 * self.team.wins) - self.team.losses + [self.team.league findConference:self.team.conference].confPrestige;
```

In English: the growth and success of your team is paramount. Talent ratings don't matter -- it's what you do with the talent on your roster that counts. This factor is then balanced by a few other factors: the quality of teams you beat, the number of teams you beat, and the prestige of your conference. 

In summary: if you win a lot of games in a tough conference (therefore generate a big prestige bump), you'll have a high coach score.
