### ISSUE TITLE
Custom player names

### ISSUE THREAD

**Issue by trojanpatriot** [akeaswaran/cfc-bugs#100]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
We should be able to customize the player names

**Comment by akeaswaran** [comment]
This is already supported in-game -- during any offseason, you can customize the name of any player on your team by heading to their profile and tapping the edit icon in the top right corner of the screen (should look like a pad and pencil).
