### ISSUE TITLE
Prestige Fluxuation and Job loss

### ISSUE THREAD

**Issue by bmarqs** [akeaswaran/cfc-bugs#101]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when.   I’ve found that it’s too easy to lose and too hard to gain prestige.

**Describe the solution you'd like**
It should simply be less prestige taken after a bad season or there needs to be a smaller range of an expected season. If I go 3-9 and then two years later go 9-4 and I lost 11 prestige the 3-9 season I’ll get fired because 9-4 is “expected” and I’ll gain none of the 11 prestige I lost back. Even if I win the national Championship I may only equal that 11 gained prestige back and most likely not. That simply has to be changed.

**Describe alternatives you've considered**
I think despite the issues with being fired too quickly that becoming a coordinator after being fired would be more realistic. If I go 3-9 at a team with low prestige I shouldn’t be able to be offered a head coach position at a team better than 3-9 and probably not at all.

**Additional context**

**Comment by akeaswaran** [comment]
I've built out a more deterministic way to evaluate performance in the next release. This should alleviate some of the issues you've experienced.
