### ISSUE TITLE
Scouting

### ISSUE THREAD

**Issue by MannyB617** [akeaswaran/cfc-bugs#102]
I wanna say the game is very fun as it is and I think y’all are doing a wonderful job. I think scouting recruits would be a fun way to change it up a little. It could be a new way to find a player’s potential instead of being given, or a way figure out their overall to know if they are gems or busts. This could either be done during the season or done before recruiting begins, but I would recommend making it separate from recruitment effort. You could also make a new coach attribute through scouting, which can effect how much scouting effort is given per year. Keep up the strong work comrades :)

**Comment by akeaswaran** [comment]
In-season recruiting is being considered for a future release (note: this is not a promise that it will appear in the game OR a timeline; it's just a promise that I will consider it).
