### ISSUE TITLE
Not Able to Hire OC/DC on IOS

### ISSUE THREAD

**Issue by Kyleellis77** [akeaswaran/cfc-bugs#103]
I am in the off-season for my franchise and I just fired my DC and my OC’s contract expired. I was able to sign another OC, but when I went to sign a DC it would ask me how many years I want to sign him for and the only option was for me to cancel, not letting me sign him. This left me stuck in the off-season without a DC and I am now not able to continue my franchise.

**Comment by akeaswaran** [comment]
This happens because you are out of offseason effort -- I have a patch for this working in a future release.
