### ISSUE TITLE
Bowl Name Rebrand Freeze

### ISSUE THREAD

**Issue by HobbesTHero** [akeaswaran/cfc-bugs#106]
Please fill out the template below to make sure I can assist you most effectively.

Whenever rebranding Bowl names on with a custom metadata the game freezes. (After entering the name and selecting apply.) I was at the end of season two, but I’m not sure if that effects it.

1. Select the rebrand Bowl games thing
2. Click on any Bowl game
3. Change name and select apply
4. Game freezes

iOS 14.3
4.2.7
iPhone 7 Plus
Not Jailbroken
It occurs each time. It doesn’t work with unedited metadata. As previously stated not sure if it works before the end of season two. Also team and conference edits are fine.
Game Freezes
Video: https://youtu.be/IiHl0E4ol4E
My email is boldenzr@gmail.com if there is anything you need from me.

Note: Just checked. After you complete the offseason and get to the option of playing the week one game you can edit them.

**Comment by akeaswaran** [comment]
This will be fixed in an upcoming release. Thanks for reporting it!
