### ISSUE TITLE
Face Scan/ Award Winning (All Skill Positions)

### ISSUE THREAD

**Issue by Deuce22Tx** [akeaswaran/cfc-bugs#107]
The game is very awesome it would be a lot better if there was a lot more scenery in the game like faces scans or even a menu that shows Award winnings. The game is great but once u play it for a while it’s get boring Snd dry. There should be more scenery.

**Comment by akeaswaran** [comment]
I don't make money from this game, and therefore I do not have money to pay for licenses to player likenesses (which 1. are not an NCAA-allowed option and 2. even if they were, they would cost many thousands of dollars) to use via face scan or otherwise.

**Comment by Deuce22Tx** [comment]
Ohhh ok I see I played some with faces I didn’t know it would cost money.. thank you 

J
