### ISSUE TITLE
Recruiting Rankings too dependent on number of recruits

### ISSUE THREAD

**Issue by pfightingirish** [akeaswaran/cfc-bugs#109]
Please fill out the template below to make sure I can assist you most effectively.

**Describe the bug**
Recruiting rankings are way off. The top teams seemed to have recruited a lot of players (22 players for the top ranked team), but they are all rated in the 50s, 60s, and 70s, with the highest rated player being a 3-star rated as 74. 

**To Reproduce**

**iOS version**: Version of iOS this bug occurred on (can be found in Settings.app > General) iOS latest version.
**CFC version**: Version of CFC this bug occurred on (can be found in CFC's My Team/Career tab > Gear icon > scroll to the bottom)
**iOS device**: For example iPhone XS, iPad mini, etc.
**Jailbroken**: Whether or not your device is jailbroken
**Reproducible:** Can you reproduce it every time? Or is it random?

**Expected behavior**
I would have expected more traditional rankings, with the normal top teams like Florida and Georgia who pull in 4 and 5 stars to be rated the highest. Not a bunch of scrub teams with very low prestige.

**Screenshots**
If possible, add screenshots to help show the problem.
![989450F2-BAF9-4B68-BE6C-8F53E68F00F5](https://user-images.githubusercontent.com/76876222/104861921-a4387400-58ff-11eb-8763-f74af875dc42.png)
![3DBAA96B-0033-4181-A2C5-418B8245D87B](https://user-images.githubusercontent.com/76876222/104861924-a6023780-58ff-11eb-8bdb-7cef0b7a8ef2.png)

**Video**
If possible, attach a video to help show the problem. You can attach a video by uploading it to Streamable, Gfycat, YouTube, etc. and pasting the URL here.

**Additional context**

**Comment by akeaswaran** [comment]
I think this should be fixed in the next release. There seemed to be an underlying bug in how those recruiting class scores were calculated.
