### ISSUE TITLE
Punt distances are miscalculated

### ISSUE THREAD

**Issue by appyno35** [akeaswaran/cfc-bugs#11]
Please fill out the template below to make sure I can assist you most effectively.

**Describe the bug**
Punts aren’t going as far as it says they are. It says the punt went for a net of 25 yards but will only go to the old first down marker.

**iOS version**: Version of iOS this bug occurred on (can be found in Settings.app > General)
13.4.1
**CFC version**: Version of CFC this bug occurred on (can be found in CFC's My Team/Career tab > Gear icon > scroll to the bottom)
4.1 beta
**iOS device**: For example iPhone XS, iPad mini, etc.
iPhone 8
**Jailbroken**: Whether or not your device is jailbroken
It’s not
**Reproducible:** Can you reproduce it every time? Or is it random? 
Yes every time

**Comment by akeaswaran** [comment]
Tweaking this in the next beta -- thanks for reporting!
