### ISSUE TITLE
Difficulty’s 

### ISSUE THREAD

**Issue by Megabot51** [akeaswaran/cfc-bugs#111]
I think you should add difficulty’s as like an experiment for players that want high scoring games or blowouts or hard mode for the competitive players and tournaments to see which players are the best in the game and add a pro mode for like pro teams! if you like any of my ideas please email me
@megaprimezero@gmail.com
-Shane

**Comment by akeaswaran** [comment]
Thanks for the feedback!

There's already a Hard difficulty in the game. I'm not looking at adding more.

Head-to-head multiplayer is under consideration for a future release, but there will not be any sort of central organization of tournaments. That requires resources that I do not have.

There will be no pro football mode/game.

**Comment by Megabot51** [comment]
Is there a pro football coach for iOS

**Comment by akeaswaran** [comment]
There is not.

**Comment by Megabot51** [comment]
Ok, thanks. Is there an easy mode

**Comment by akeaswaran** [comment]
The easy difficulty is the default for the game. You can pick which difficulty is used when creating a new save file. You can not swap between difficulties in the middle of a save file.
