### ISSUE TITLE
Overly aggressive prestige reductions

### ISSUE THREAD

**Issue by pfightingirish** [akeaswaran/cfc-bugs#114]
edited with more information

I started with a lowly team and built their prestige up from low 60s to 82, last year (year 2025) I went 8-5 winning both bowl game and rivalry game, with a W-L record in line with expectations, and had some players drafted but my prestige dropped 20 points, taking me below where I started. I could understand no change, or even a slight increase or decrease, but not a 20 point decrease. Pictures included in case I am not being clear. I didn’t see any sanction at the beginning of the year, but the message at the end mentioned something about sanctions, what impact could that have?

Thank you for everything you do for this game, I hope this feedback helps as you continually improve this already great game.

**Describe the bug**
![B365245F-0389-4EA6-A942-4FC3D55F90E7](https://user-images.githubusercontent.com/76876222/106385927-a3441f80-63a0-11eb-972e-53084d4f8454.png)
![C11C89CF-CB01-4D76-B1C0-9F4DBF9C0BF1](https://user-images.githubusercontent.com/76876222/106385932-a9d29700-63a0-11eb-8e55-c3ed227ea621.png)
![322A151F-8313-45FE-B45D-78C0048BC0D1](https://user-images.githubusercontent.com/76876222/106385934-a9d29700-63a0-11eb-96f2-100b1c5bce9a.png)

**To Reproduce**

**iOS version**: Version of iOS this bug occurred on (can be found in Settings.app > General)
**CFC version**: Version of CFC this bug occurred on (can be found in CFC's My Team/Career tab > Gear icon > scroll to the bottom)
**iOS device**: For example iPhone XS, iPad mini, etc.
**Jailbroken**: Whether or not your device is jailbroken
**Reproducible:** Can you reproduce it every time? Or is it random?

**Expected behavior**

**Screenshots**
If possible, add screenshots to help show the problem.

**Video**
If possible, attach a video to help show the problem. You can attach a video by uploading it to Streamable, Gfycat, YouTube, etc. and pasting the URL here.

**Additional context**

**Comment by akeaswaran** [comment]
> I didn’t see any sanction at the beginning of the year, but the message at the end mentioned something about sanctions, what impact could that have?

You were indeed hit by sanctions -- the code is pretty specific about how it generates the season summary string and why it includes specific information.
