### ISSUE TITLE
Edits

### ISSUE THREAD

**Issue by JussGotti** [akeaswaran/cfc-bugs#115]
No Problems I love the game. Only thing is, I wish you had to wear we could edit like say a stadium or jerseys or the names and attributes or even control the game like analog stick And buttons

**Comment by akeaswaran** [comment]
You can edit team names and colors using metadata or from the team profile pages. You can edit player names from player profile pages. You will also be able to edit player information in bulk using metadata files in a future release.

I will not be supporting any other form of game control other than the play-calling selection that currently exists. This game is not meant to be a 1:1 replacement for multimillion dollar franchises like EA Sports' NCAA Football series -- it's just a simple, streamlined football experience that scratches a similar itch.
