### ISSUE TITLE
Off-season recruiting bug

### ISSUE THREAD

**Issue by KermitTheFrog69420** [akeaswaran/cfc-bugs#122]
Please fill out the template below to make sure I can assist you most effectively.

**Describe the bug**
The bug is when you are on the off-season and you are recruiting, when you go to recruiting and you select apply all on the first recruit that you pick for that position type, 50% of the time it will scroll you all the way up to the top of the recruiting list for the position type, after that first apply all it doesn’t happen again.

**To Reproduce**
1. Go to 'Recruiting during off-season '
2. Click on 'Apply all on any recruit that is in your certain positional type'
3. Scroll down to '50% of the time it will then scroll you back up to the very top of the recruiting list for that position'

**iOS version**: Version of iOS this bug occurred on (can be found in Settings.app > General)
**CFC version**: Version of CFC this bug occurred on (can be found in CFC's My Team/Career tab > Gear icon > scroll to the bottom)
**iOS device**: IPhone 11
**Jailbroken**: Whether or not your device is jailbroken: No
**Reproducible:** Can you reproduce it every time? Or is it random? Mostly random

**Expected behavior**
A clear and concise description of what you expected to happen. I expect to hit apply all and stay where I am on the recruiting list and not be taken back to the top

**Screenshots**
If possible, add screenshots to help show the problem. Not possible

**Video**
If possible, attach a video to help show the problem. You can attach a video by uploading it to Streamable, Gfycat, YouTube, etc. and pasting the URL here. 

https://share.icloud.com/photos/0SyhVIJ-5vD9PjkYLN9rrXTNg

**Additional context**

**Comment by akeaswaran** [comment]
This flow is getting rebuilt in the next release, so this issue should be taken care of soon. Thanks for sending this over!
