### ISSUE TITLE
Increase difficulty

### ISSUE THREAD

**Issue by pfightingirish** [akeaswaran/cfc-bugs#124]
**Is your feature request related to a problem? Please describe.**
Would it be possible to increase the difficulty in “hard mode”? I don’t have a particularly great team but am demolishing the competition. I think having the games be more competitive would make the game more interesting.
![23DC6BF1-8CE2-48CC-B8EF-4296209988F8](https://user-images.githubusercontent.com/76876222/110193558-9af95d00-7e02-11eb-8eb8-4101ceee774b.png)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by akeaswaran** [comment]
Unfortunately, I have no plans to increase difficulty or add another difficulty to the game. If you've already built a world-beating dynasty in hard mode, then, congrats: you've beaten the game.
