### ISSUE TITLE
Coordinator 

### ISSUE THREAD

**Issue by trahp** [akeaswaran/cfc-bugs#125]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...] I don’t have an issue but I think it would be cool to add an offensive coordinator and defensive coordinator position that you can be instead of just HC and also make it where some 5 stars are available even with a bad school

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by akeaswaran** [comment]
> add an offensive coordinator and defensive coordinator position that you can be instead of just HC

Starting a career as a coordinator is under consideration for a future release (note: this is not a promise that this feature will appear in the game, only that I will consider it).

> make it where some 5 stars are available even with a bad school

This mechanic will not be changing; it would not be realistic for low-prestige schools to net five-star recruits. Sorry.
