### ISSUE TITLE
Rename any colleges to your liking 🤩

### ISSUE THREAD

**Issue by samujovalencia8** [akeaswaran/cfc-bugs#126]
Renaming Colleges. 

One of the things that is missing to this amazing is, customization. Customizing a team to the user’s liking can make a difference to playing a game that is with auto-generated and playing with Colleges such as Ohio State, Clemson, etc. This feature will be a game changer.

**Comment by akeaswaran** [comment]
You can already do this. At the end of a season (IE: after the national championship game), you can head to any team profile page and tap the button in the top-right corner of the screen (it'll look like a pad and pencil). 

Alternatively, you can use metadata files for bulk customization.
