### ISSUE TITLE
Bugs and crashes

### ISSUE THREAD

**Issue by bman2** [akeaswaran/cfc-bugs#129]
There are way too many crashes and bugs in this version. Also I am not able to save my metadata anywhere. It should be able to give me a url so I can plug it back in whenever

**Comment by akeaswaran** [comment]
I am working on taking care of bugs and crashes as they come up. More information about what you're experiencing would be appreciated.

> Also I am not able to save my metadata anywhere. It should be able to give me a url so I can plug it back in whenever

This would require a web storage server with monthly storage costs, and I do not have the capital nor the time to manage that. There's a wide number of other cloud file hosting services that fit this need (Dropbox, GitHub Gists, etc). If you're interested in building your own metadata file, I strongly suggest you pick a service you're comfortable with and edit your file there.

**Comment by akeaswaran** [comment]
Closed without response.
