### ISSUE TITLE
More than 12 conferences.

### ISSUE THREAD

**Issue by HobbesTHero** [akeaswaran/cfc-bugs#130]
A feature I think would be cool is allowing more than 12 conferences through metadata. The default would still be 12 but if you wanted to do say, 13 you can if you create the metadata. Conferences would still only have 10 teams in them, I don’t think that should change, but you can do, say, 12-18 conferences if you want. A suggestion for this is that conference promotion/relegation would disabled if there is an odd number of conferences.

**Comment by akeaswaran** [comment]
I'm not planning on expanding the field of teams, unfortunately. Sorry.
