### ISSUE TITLE
Corrupt saves after season 3

### ISSUE THREAD

**Issue by Pistol23** [akeaswaran/cfc-bugs#133]
Please fill out the template below to make sure I can assist you most effectively.

**Describe the bug**
The game save gets corrupted after season 3, after I’ve left the game and try to play again later.

**To Reproduce**
1. Play to season 3
2. Log out of game
3. Try to load saved game
4. Says save is corrupted 

**iOS version**) 14.4.2
**CFC version**: Version of CFC this bug occurred on (can be found in CFC's My Team/Career tab > Gear icon > scroll to the bottom)
**iOS device** iPhone 11
**Jailbroken**: Whether or not your device is jailbroken Yes
**Reproducible:** Can you reproduce it every time? Or is it random? Every Time

**Expected behavior**

**Screenshots**
If possible, add screenshots to help show the problem.

**Video**
If possible, attach a video to help show the problem. You can attach a video by uploading it to Streamable, Gfycat, YouTube, etc. and pasting the URL here.

**Additional context**

**Comment by akeaswaran** [comment]
This issue is under investigation. More details available here: https://reddit.com/r/FootballCoach/comments/mrv2ga/_/guorp7l/?context=1

**Comment by akeaswaran** [comment]
This issue should be fixed in 5.0.5. Please let me know if you run into issues once that update rolls out.
