### ISSUE TITLE
Conference Movement

### ISSUE THREAD

**Issue by domdaddy1230** [akeaswaran/cfc-bugs#134]
**Is your feature request related to a problem? Please describe.**

I’d like the ability to move out of a conference and into a different one. (E.G. Maryland into the Big 12) 
**Describe alternatives you've considered**
Purposely losing a season to get demoted from conference and then winning at lower level to get into a larger one again isnt very convenient 

**Additional context**

**Comment by akeaswaran** [comment]
I am not planning on supporting in-game conference realignment outside of promotion/relegation. Given this, the problem you describe may best be solved by editing a metadata file to put schools in the conferences you want.
