### ISSUE TITLE
Please provide a descriptive title here, then fill out the rest of the template.

### ISSUE THREAD

**Issue by wcmiller4** [akeaswaran/cfc-bugs#136]
Please fill out the template below to make sure I can assist you most effectively.

**Describe the bug**
The latest update will not allow me to play the game (continue my season) brings up new home screen and shows my season... I click on it and it tells me I new a new version. I did the update I had, so I should be current on updates
**To Reproduce**

**iOS version**: Version of iOS this bug occurred on (can be found in Settings.app > General) software version 14.4
**CFC version**: Version of CFC this bug occurred on (can be found in CFC's My Team/Career tab > Gear icon > scroll to the bottom) version 5.0.4 (3)
**iOS device**: For example iPhone XS, iPad mini, etc. iPhone 12 Pro Max 
**Jailbroken**: Whether or not your device is jailbroken
**Reproducible:** Can you reproduce it every time? Or is it random?

**Expected behavior**
A clear and concise description of what you expected to happen. The update, unless I’m missing something I can’t play, also afraid to loss all my data

**Screenshots**
If possible, add screenshots to help show the problem.

**Video**
If possible, attach a video to help show the problem. You can attach a video by uploading it to Streamable, Gfycat, YouTube, etc. and pasting the URL here.

**Additional context**

**Comment by akeaswaran** [comment]
I am guessing you ran into the Save File Corrupt bug that a lot of others have been having trouble with lately -- this should be taken care of on version 5.0.5, which has rolled out on the App Store over the last few days. Please download and install this version. You should be able to play normally thereafter.

**Comment by wcmiller4** [comment]
Still having issues have not been able to play since update... I do have the latest update
