### ISSUE TITLE
Retire Coach Option

### ISSUE THREAD

**Issue by domdaddy1230** [akeaswaran/cfc-bugs#137]
I’d like to be able to retire my coach after I am done playing a certain school so I can add them to the leaderboard without having to play until 60 years old or whatever the number may be.

I’d also like to just sort recruits by strong interest regardless of what the interest number may actually be 

and timeouts during games so i don’t get screwed on a last second drive 😔

in love with this game so proud of what it’s become since 2016

**Comment by akeaswaran** [comment]
> I’d like to be able to retire my coach after I am done playing a certain school so I can add them to the leaderboard without having to play until 60 years old or whatever the number may be.

This will be supported in a future update. Thanks for the suggestion!

> I’d also like to just sort recruits by strong interest regardless of what the interest number may actually be

This is now supported as of 5.1.

> and timeouts during games so i don’t get screwed on a last second drive

Unfortunately, I'm not planning on making any major changes to the game simulations like timeouts, running clock, etc as we move towards the end of active development. Sorry.
