### ISSUE TITLE
Please provide a descriptive title here, then fill out the rest of the template.

### ISSUE THREAD

**Issue by iamtay** [akeaswaran/cfc-bugs#14]
Please fill out the template below to make sure I can assist you most effectively.

**Describe the bug**

**To Reproduc

**iOS version**: Version of iOS this bug occurred on (can be found in Settings.app > General)
**CFC version**: Version of CFC this bug occurred on (can be found in CFC's My Team/Career tab > Gear icon > scroll to the bottom)
**iOS device**: For example iPhone XS, iPad mini, etc.
**Jailbroken**: Whether or not your device is jailbroken
**Reproducible:** Can you reproduce it every time? Or is it random?

**Expected behavior**

**Screenshots**
If possible, add screenshots to help show the problem.

**Video**
If possible, attach a video to help show the problem. You can attach a video by uploading it to Streamable, Gfycat, YouTube, etc. and pasting the URL here.

**Additional context**

**Comment by iamtay** [comment]
Cannot see other offers nor can change the coach name

**Comment by akeaswaran** [comment]
Please fill out the template and add more detail to this ticket.

**Comment by akeaswaran** [comment]
Closed because of no response.
