### ISSUE TITLE
Constant bad save files 

### ISSUE THREAD

**Issue by gol4tim** [akeaswaran/cfc-bugs#140]
Please fill out the template below to make sure I can assist you most effectively.

**Describe the bug**
A clear and concise description of what the bug is - Within a season, the save files are purportedly becoming corrupted. 

**To Reproduce**
1. Click on saved file. 

2. Get message about corruption and have to start over again. 

**iOS version**: Version of iOS this bug occurred on (can be found in Settings.app > General)
**CFC version**: Version of CFC this bug occurred on (can be found in CFC's My Team/Career tab > Gear icon > scroll to the bottom)
**iOS device*. iPhone 11
**Jailbroken**: Whether or not your device is jailbroken
**Reproducible:** Can you reproduce it every time? Or is it random?  Random 

**Expected behavior**

**Screenshots**
If possible, add screenshots to help show the problem.

**Video**
If possible, attach a video to help show the problem. You can attach a video by uploading it to Streamable, Gfycat, YouTube, etc. and pasting the URL here.

**Additional context**

**Comment by akeaswaran** [comment]
I am working on a fix. Sorry for the inconvenience.

**Comment by gol4tim** [comment]
It would be nice to find out when the fix is available so that I can avoid the game until that time.

Sent from my iPhone

On Apr 30, 2021, at 10:06 PM, Akshay Easwaran ***@***.***> wrote:

﻿

I am working on a fix. Sorry for the inconvenience.

**Comment by akeaswaran** [comment]
I don't have a time estimate at this point, and I usually avoid giving those out because fixing tricky bugs like this one is an inexact science. The best I can do is say that a fix will be out soon.

**Comment by gol4tim** [comment]
I understand. Is there a way for me to tell when the fix is done? Thanks.

Sent from my iPhone

On May 2, 2021, at 7:42 PM, Akshay Easwaran ***@***.***> wrote:

﻿

I don't have a time estimate at this point, and I usually avoid giving those out because fixing tricky bugs like this one is an inexact science. The best I can do is say that a fix will be out soon.

**Comment by akeaswaran** [comment]
Just keep an eye on the App Store for any updates.
