### ISSUE TITLE
Ideas

### ISSUE THREAD

**Issue by clarencejit** [akeaswaran/cfc-bugs#141]
1. Add a Athlete pos (they play multiple pos in hs, and you can decide what they play in college)
2. Why does my file keep corrupting 
3. Please make a basketball one March madness would be sick 

Thank you and have a good day

**Comment by akeaswaran** [comment]
1. I'm not planning on supporting this. Sorry. 
2. I'm working on a fix. Sorry for the inconvenience.
3. I'm not working on any other games, nor do I plan to. My focus is to make CFC the best it can be during the rest of its period of active development. Sorry.

**Comment by clarencejit** [comment]
Don’t be sorry I completely understand, thank you for responding so fast!

Sent from my iPhone

On Apr 30, 2021, at 9:55 PM, Akshay Easwaran ***@***.***> wrote:

﻿

  1.  I'm not planning on supporting this. Sorry.
  2.  I'm working on a fix. Sorry for the inconvenience.
  3.  I'm not working on any other games, nor do I plan to. My focus is to make CFC the best it can be during the rest of its period of active development. Sorry.
