### ISSUE TITLE
File corruption  

### ISSUE THREAD

**Issue by strongest1019** [akeaswaran/cfc-bugs#142]
Please fill out the template below to make sure I can assist you most effectively.

**Describe the bug**

**To Reproduce**

**iOS version**: Version of iOS this bug occurred on (can be found in Settings.app > General)
**CFC version**: Version of CFC this bug occurred on (can be found in CFC's My Team/Career tab > Gear icon > scroll to the bottom)
**iOS device**: For example iPhone XS, iPad mini, etc.
**Jailbroken**: Whether or not your device is jailbroken
**Save File Config**: The configuration you have enabled in your save file.
- Mode (Career or School/Normal)
- Difficulty (Easy or Hard)
- Manage Coaching Staff (On or Off)
- Promotion/Relegation (On or Off)
- Automated Recruiting (On or Off)

**Reproducible:** Can you reproduce it every time? Or is it random?

**Expected behavior**

**Screenshots**
If possible, add screenshots to help show the problem.

**Video**
If possible, attach a video to help show the problem. You can attach a video by uploading it to Streamable, Gfycat, YouTube, etc. and pasting the URL here.

**Additional context**
Hi I’ve been playing this game for some weeks now and every time the second season comes around for me, somehow I get a message when logging back in that my file was corrupt having me to start over every time.

**Comment by akeaswaran** [comment]
I am working on a fix, but please fill out the template plus the questions here so I can better diagnose the issue: https://reddit.com/r/FootballCoach/comments/n3jdkq/cfc_for_ios_save_file_corruption_investigation/

**Comment by akeaswaran** [comment]
Fixed in 5.0.6.

**Comment by strongest1019** [comment]
Awesome! I just experienced another corrupted file the other day as well. I was going to report it but something told me to wait. Glad to hear it’s all fixed!

Grace and Peace
Iron sharpens iron
