### ISSUE TITLE
Interviews

### ISSUE THREAD

**Issue by Eryk-ops** [akeaswaran/cfc-bugs#150]
I love the game but it’s a little bare. It would be nice to see what your players projected to be drafted at. I also wish their was interviews. Like after a game a screen pops up with questions to answer if you won/lost a game ect. Also maybe a interview system to recruit players onto your team

**Comment by akeaswaran** [comment]
> It would be nice to see what your players projected to be drafted at.

This is already a feature in v5.0.

Re: interviews -- I'm not really interested in adding a mechanic like this. The game is more of a "team management simulator" than a "coach experience simulator", so something like this just wouldn't fit into the theme of the game. However, regarding your last point about recruiting players onto your team via interview, the existing competitive recruiting system already does something like this, as you are able to take various actions to raise a recruit's interest in your program.

Thanks for the feedback!
