### ISSUE TITLE
Corrupt file

### ISSUE THREAD

**Issue by joe-brookes** [akeaswaran/cfc-bugs#152]
Hey
30 seasons file corrupt 🙄
![13FADC93-97F5-458C-AECE-F44C28CC521C](https://user-images.githubusercontent.com/81857760/120472569-f43f4100-c39d-11eb-9ffa-96da4278f96d.png) any way this can be corrected before I delete it?

**Comment by akeaswaran** [comment]
This should be fixed in 5.0.7, which will be available soon.
