### ISSUE TITLE
coach signing bug

### ISSUE THREAD

**Issue by berto1008** [akeaswaran/cfc-bugs#155]
![EE511400-05E0-41A0-842A-4947E57D97EC](https://user-images.githubusercontent.com/85618391/121340533-bbe3b980-c8ed-11eb-87bd-154694d56229.png)
when i clicked to sign my defensive coordinator it ask me how many years i want to sign him but doesn’t show any years i can offer him and just give me the option to press cancel.

**Comment by akeaswaran** [comment]
This issue will be fixed in the next update. Thanks for reporting it!
