### ISSUE TITLE
Additional feature that may make the game better

### ISSUE THREAD

**Issue by nateumbar** [akeaswaran/cfc-bugs#156]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by nateumbar** [comment]
Hi,

I believe that if you add recruiting for 2 years after the game can improve and you should definitely make a college basketball game!

**Comment by akeaswaran** [comment]
> I believe that if you add recruiting for 2 years after

I'm not entirely sure what you mean by this. If you're looking for extending recruiting to include high school juniors, that is not something I plan on adding to the game. Sorry.

> you should definitely make a college basketball game!

Unfortunately, I do not have any plans to make any other games. I am focused on making CFC for iOS the best it can be.
