### ISSUE TITLE
Rivalry and OT

### ISSUE THREAD

**Issue by twdavis71** [akeaswaran/cfc-bugs#16]
**Is your feature request related to a problem? Please describe.**
1)Overtime games sometimes glitch. I score then forward to Next Possession to let it simulate Defense and it stops them, but only way for game to end is for me to call defensive plays. 
2) set rivalries - I have had several runs where a team doesn’t have a rivalry and each year summary shows it as a tie

**Describe the solution you'd like**
Overtime to end upon completion, and a way to set/change rivalries for this fun feature!

**Describe alternatives you've considered**
N/a

**Additional context**

**Comment by akeaswaran** [comment]
> I have had several runs where a team doesn’t have a rivalry and each year summary shows it as a tie

This would only happen in metadata files where a team does not have a rival configured. Rivals come in pairs in the base team file, and if this pairing isn't respected in the metadata file, then you'll see weird results like that.

However, I do understand the point about being able to set your own rival, so I'll consider it for a future release. Thanks for the suggestion!

**Comment by akeaswaran** [comment]
Rivalry customization was added in a 5.x release, and I haven't been able to reproduce this bug for overtime unfortunately. Closing this issue.
