### ISSUE TITLE
Offensive/Defensive Coordinator

### ISSUE THREAD

**Issue by TonyMontana71** [akeaswaran/cfc-bugs#163]
Would be really cool if you could add in the ability to start as an Offensive coordinator or defensive coordinator when beginning your career. And if you get fired from your job, most of your offers are gonna be coordinator positions not HC somewhere.

**Comment by akeaswaran** [comment]
Unfortunately, this feature was cut from consideration for future versions. More details here: https://www.reddit.com/r/FootballCoach/comments/ovn6n7/cfc_for_ios_v51_beta/
