### ISSUE TITLE
Game crashes constantly 

### ISSUE THREAD

**Issue by RascalSqueaker** [akeaswaran/cfc-bugs#165]
Please fill out the template below to make sure I can assist you most effectively.

The game crashes constantly. There will be a message saying that the save file is corrupted and can no longer be played. The iCloud save will not restore the game without changing the parameters (ie hard to easy mode). I’ve played many seasons all the way through but now it is impossible - I’ll get maybe 10-15 seasons in, and something happens to corrupt the save file, and I have to start all over.  It’s very frustrating. 

**Describe the bug**

**To Reproduce**

**iOS version**: Version of iOS this bug occurred on (can be found in Settings.app > General)
**CFC version**: Version of CFC this bug occurred on (can be found in CFC's My Team/Career tab > Gear icon > scroll to the bottom)
**iOS device**: For example iPhone XS, iPad mini, etc.
**Jailbroken**: Whether or not your device is jailbroken
**Save File Config**: The configuration you have enabled in your save file.
- Mode (Career or School/Normal)
- Difficulty (Easy or Hard)
- Manage Coaching Staff (On or Off)
- Promotion/Relegation (On or Off)
- Automated Recruiting (On or Off)

**Reproducible:** Can you reproduce it every time? Or is it random?

**Expected behavior**

**Screenshots**
If possible, add screenshots to help show the problem.

**Video**
If possible, attach a video to help show the problem. You can attach a video by uploading it to Streamable, Gfycat, YouTube, etc. and pasting the URL here.

**Additional context**

**Comment by akeaswaran** [comment]
Can you please email me a save file that has corrupted? I have been update to reproduce this new save file corruption issue and having something in hand from someone experiencing it would be helpful.

If you used a metadata file to create this save file, please send me a link to that as well.

**Comment by akeaswaran** [comment]
Closed without response.
