### ISSUE TITLE
Please provide a descriptive title here, then fill out the rest of the template.

### ISSUE THREAD

**Issue by Nbatoff** [akeaswaran/cfc-bugs#166]
Please fill out the template below to make sure I can assist you most effectively.

**Describe the bug**
Corrupt save file version 5.0.8. I saved it to iCloud so I can continue the save but now I have to on easy mode because my school is no longer in the bottom two in the conference. 
**To Reproduce**

**iOS version**: Version of iOS this bug occurred on (can be found in Settings.app > General) 14.6
**CFC version**: Version of CFC this bug occurred on (can be found in CFC's My Team/Career tab > Gear icon > scroll to the bottom) 5.0.8
**iOS device**: For example iPhone XS, iPad mini, etc. iPhone 12 Pro 
**Jailbroken**: Whether or not your device is jailbroken No
**Save File Config**: The configuration you have enabled in your save file.
- Mode (Career or School/Normal) Career
- Difficulty (Easy or Hard) Hard
- Manage Coaching Staff (On or Off) On
- Promotion/Relegation (On or Off) Off
- Automated Recruiting (On or Off) Off

**Reproducible:** Can you reproduce it every time? Or is it random?

**Expected behavior**

**Screenshots**
If possible, add screenshots to help show the problem.

**Video**
If possible, attach a video to help show the problem. You can attach a video by uploading it to Streamable, Gfycat, YouTube, etc. and pasting the URL here.

**Additional context**

**Comment by akeaswaran** [comment]
This will be fixed in 5.1.
