### ISSUE TITLE
Please provide a descriptive title here, then fill out the rest of the template.

### ISSUE THREAD

**Issue by AlexDabbs** [akeaswaran/cfc-bugs#167]
Please fill out the template below to make sure I can assist you most effectively.

**Describe the bug**

For no reason WHAT SO EVER the save files decide to randomly corrupt and become unplayable! No I didn’t close the app when it was saving or changing the roster or mid game or during the off-season! This makes 3 files that have been corrupted for me! I honestly love this game and it is super fun, but it’s just very frustrating when a game you put time in to playing and working on suddenly corrupts and is gone forever!

**To Reproduce**

The only way I know of reproducing it is when you close the app during something (literally anything) and then you go to play it again and it says the files is corrupted.

**iOS version**: Version of iOS this bug occurred on (can be found in Settings.app > General)
IOS 14.4.1
**CFC version**: Version of CFC this bug occurred on (can be found in CFC's My Team/Career tab > Gear icon > scroll to the bottom)
5.0.8
**iOS device**: For example iPhone XS, iPad mini, etc.
iPhone 11 plus
**Jailbroken**: Whether or not your device is jailbroken
Nope not jailbroken
**Save File Config**: The configuration you have enabled in your save file.
- Mode (Career or School/Normal) - Career
- Difficulty (Easy or Hard) - Easy
- Manage Coaching Staff (On or Off) - Off
- Promotion/Relegation (On or Off) - off
- Automated Recruiting (On or Off) - off

**Reproducible:** Can you reproduce it every time? Or is it random?
Random from what I’ve seen!

**Expected behavior**
Allow me to play the game without fear of having my save files get corrupted!! Seriously!

**Screenshots**
If possible, add screenshots to help show the problem.

**Video**
If possible, attach a video to help show the problem. You can attach a video by uploading it to Streamable, Gfycat, YouTube, etc. and pasting the URL here.

**Additional context**
Sorry if I sound rude, but this is a major problem!!

**Comment by akeaswaran** [comment]
This will be fixed in 5.1.
