### ISSUE TITLE
Switching between easy and hard mode.

### ISSUE THREAD

**Issue by Nbatoff** [akeaswaran/cfc-bugs#168]
**Is your feature request related to a problem? Please describe.**
My save file corrupted and I can only access my save through the iCloud backup I had. The only issue is I now have to play on easy mode because my team is no longer one of the bottom two teams in the conference. 
**Describe the solution you'd like**
I would like to be able to play hard mode with this save again. 
**Describe alternatives you've considered**
I don’t think there is a solution other than to be able to switch difficulty in the settings option when in a save file.
**Additional context**

**Comment by akeaswaran** [comment]
IMO, the best solution here is fix the source problem (save file corruption), not support a buggy workaround. The issue is on my radar, and I'm working on it. I'll provide an update on Reddit when possible.
