### ISSUE TITLE
In game substitutions, single player position or even just a mass sub to the backups

### ISSUE THREAD

**Issue by paradox102** [akeaswaran/cfc-bugs#17]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by akeaswaran** [comment]
I appreciate the suggestion, but unfortunately, this goes against one of the core design principles of the game (which you can read about [here](https://www.reddit.com/r/FootballCoach/comments/cgkyna/cfc_40_update/) -- I actually used this idea as an example).
