### ISSUE TITLE
Please provide a descriptive title here, then fill out the rest of the template.

### ISSUE THREAD

**Issue by GoBeavs92** [akeaswaran/cfc-bugs#171]
Sometimes when I randomly put the game in the background (I don’t close it out), I come back to a ‘corrupt file’ message and have to restart again. I noticed it happens more when I go to open the file later and it says, “last update: today”. Is there any way to avoid this??

**Comment by akeaswaran** [comment]
It sounds to me like the app was killed by the operating system and re-launched, which is when you saw the save file corruption message. The underlying issue with this message should be fixed in 5.1, coming soon.
