### ISSUE TITLE
CFC would be way more realistic with injuries

### ISSUE THREAD

**Issue by LeviNord** [akeaswaran/cfc-bugs#172]
**Is your feature request related to a problem? Please describe.** no, my goal is to help this game out by adding injuries further developing the games realism.
I want my players on the bench to get an opportunity to prove them self by someone getting injured, also it helps make the game more challenging because you can’t just redshirt everyone but the starters.
**Describe the solution you'd like**
I would love for you guys to add another rating called injury so if the rating was an A the person would have a low chance of getting injured but if it’s a C they would have a chance at getting injured.
**Describe alternatives you've considered**
Before I wrote this I just pretended a person got injured which is way more unrealistic then actually having injuries to the game because then I can’t choose if the guy gets injured further expanding the experience and realism to the game.
**Additional context**
No further things to add other than just saying this would help this game with giving a better experience and more realistic experience to users, plus it would be awesome if you guys could add some sort of way that some backups get in the game when your player gets tired because I recently ran my running back 64 times and in real life that’s almost impossible. More play options would be awesome as well but that’s not what I talked about here.

**Comment by LeviNord** [comment]
So like Injury's, injury rating, stamina, and stamina rating

**Comment by akeaswaran** [comment]
Injuries are already built into the game and are dependent on a durability rating, but they're just only available on the Hard difficulty. If you'd like to enable them, create a new save file and select the Hard difficulty option when configuring your settings.
