### ISSUE TITLE
College football coach can’t recruit running backs or offensive linemen 

### ISSUE THREAD

**Issue by Hudrob27** [akeaswaran/cfc-bugs#174]
Please fill out the template below to make sure I can assist you most effectively.

**Describe the bug**
on the game college football championship for IOS running backs and offensive linemen cannot be recruited. In career mode your team sucks after a few seasons because the available positions for the running backs and offensive linemen are filled by crappy walk-ons.

**To Reproduce**
1. Go to '.recruiting in offseason'
2. Click on “select positions”'
3. Scroll down to 'choose running backs and offensive linemen then go to view results.'

**iOS version**: Version of iOS this bug occurred on (can be found in Settings.app > General)
**CFC version**: Version of CFC this bug occurred on (can be found in CFC's My Team/Career tab > Gear icon > scroll to the bottom)
**iOS device**: For example iPhone XS, iPad mini, etc.
**Jailbroken**: Whether or not your device is jailbroken
**Save File Config**: The configuration you have enabled in your save file.
- Mode (Career or School/Normal)
- Difficulty (Easy or Hard)
- Manage Coaching Staff (On or Off)
- Promotion/Relegation (On or Off)
- Automated Recruiting (On or Off)

**Reproducible:** Can you reproduce it every time? Or is it random? 
It’s reproduced every time I’ve tried 

**Expected behavior**

**Screenshots**
If possible, add screenshots to help show the problem.

**Video**
If possible, attach a video to help show the problem. You can attach a video by uploading it to Streamable, Gfycat, YouTube, etc. and pasting the URL here.

**Additional context**

**Comment by akeaswaran** [comment]
I don't think this is an issue -- make sure you have archetypes properly selected for the positions you've selected. This is the usual reason why people don't see certain positions in the results.
