### ISSUE TITLE
Can’t load my 92 prestige America Somoa team

### ISSUE THREAD

**Issue by crice934** [akeaswaran/cfc-bugs#176]
![ED7DA087-2376-4553-A462-14B763808A3E](https://user-images.githubusercontent.com/89538330/130830283-15bf1849-c799-4fed-8922-6da5facdd0db.png)

**Describe the bug**
Error message when attempting to load a saved file for the college football game. Trying to get the accomplishment of win national championship on hard with America Somoa.

**To Reproduce**
1. Go to manage save files
2. Click on file 3

**iOS version**: Version of iOS this bug occurred on 14.7.1
**CFC version**: Version of CFC this bug occurred on 5.0.8(1)
**iOS device**: iPhone 7
**Jailbroken**:  not jailbroken
**Save File Config**: The configuration you have enabled in your save file.
- Mode School/Normal
- Difficulty Hard
- Manage Coaching Staff On 
- Promotion/Relegation Off
- Automated Recruiting Off

**Reproducible:** Can reproduce it every time

**Expected behavior**
Load the file so I can get that accomplishment in a season or 2.

**Screenshots**
See above

**Comment by akeaswaran** [comment]
This issue will be fixed in version 5.1, due out soon.
