### ISSUE TITLE
Have career mode on player. 

### ISSUE THREAD

**Issue by Lilpumpovo** [akeaswaran/cfc-bugs#178]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

I would love a career mode on a player. Key to helping the game more. Just wow. To be able to control your own plays. For example. Attack (opponent name.), tackle, INT, block, kick. Please just more. Let us be able to request a trade, manage our money. Give us the options of QB, WR, CB, and DL. EVEN. PLEASE.

**Describe alternatives you've considered*

**Additional context**

**Comment by akeaswaran** [comment]
This concept would be a completely different game, considering the game is named "College Football Coach". I'm currently focused on this game and making it the best it can be. Sorry.
