### ISSUE TITLE
Some additions 

### ISSUE THREAD

**Issue by camgroves13** [akeaswaran/cfc-bugs#179]
Wish we could have offensive line awards like all Americans like on android and I wish the coach hall of fame updated faster And one last thing I wish the qb run had more plays

**Comment by akeaswaran** [comment]
The game's simulation considers the offensive line to work as a unit, so given that, it doesn't make sense to give individual awards for those positions.

I'm not looking at adding more plays to the game unless the community really, really wants more. Each play is taken from a real-life playbook and hand-translated into the game, and that process is incredibly tedious and time-consuming. I'm not sure that's the best use of my limited development time moving forward unless that's something the community really, really wants to see. Sorry.
