### ISSUE TITLE
Probabilities Before Games

### ISSUE THREAD

**Issue by Maverick-USA** [akeaswaran/cfc-bugs#18]
If win probabilities can be added to the “Preview Match” (or “Match Preview”, lol ... I forgot) so they can be accessed before games, it would give users an idea of their chance of success should they choose to simulate the game. Also, maybe add wins to the season prediction feature? ...Like, the teams predicted record for the upcoming season. (That way we know exactly what we have to beat for positive prestige)... Thanks :)

**Comment by akeaswaran** [comment]
I actually wrote out the code to produce such predictions, but the algorithm used was so slow (and unable to be optimized in its current form) that it wasn't ready to ship. In the future, I'm looking to explore other solutions that'll speed up those calculations using vectorized math and functions, but that'll be a-ways off from now.

**Comment by akeaswaran** [comment]
Following up on this: this is slated for the 4.3 release. Thanks for suggesting this!
