### ISSUE TITLE
Edit Player Ratings

### ISSUE THREAD

**Issue by Jtaylor075** [akeaswaran/cfc-bugs#180]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Jtaylor075** [comment]
We should be able to edit player ratings if we wanted to like how any video game football game have it.

**Comment by akeaswaran** [comment]
You can do this for new save files via metadata files. Unfortunately, I will not be supporting in-game editing of ratings. Sorry.
