### ISSUE TITLE
Recruiting .

### ISSUE THREAD

**Issue by Scoobie227** [akeaswaran/cfc-bugs#183]
Please fill out the template below to make sure I can assist you most effectively.

**Describe the bug**
Issues when trying to search Defensive recruits

**To Reproduce**
Clicked on main recruiting. The top player is a DL, went to sort the CB’s had all states selected and nothing shows up, went to LB’s same thing, finally went to the DL and same thing. The offense does show up.

**iOS version**: 14.7.1
**CFC version**: 5.1.1
**iOS device**: iPhone X
**Jailbroken**: no
**Save File Config**: The configuration you have enabled in your save file.
- Mode (Career or School/Normal) school
- Difficulty (Easy or Hard) easy
- Manage Coaching Staff (On or Off) on
- Promotion/Relegation (On or Off) off
- Automated Recruiting (On or Off) off

**Reproducible:** Everytime

**Expected behavior**
To see all of the players

**Screenshots**
If possible, add screenshots to help show the problem.

**Video**
If possible, attach a video to help show the problem. You can attach a video by uploading it to Streamable, Gfycat, YouTube, etc. and pasting the URL here.

**Additional context**

**Comment by akeaswaran** [comment]
This isn't a bug -- make sure you have selected archetypes for the relevant positions in your filters.

**Comment by Scoobie227** [comment]
The archetypes are selected for all.

**Comment by akeaswaran** [comment]
Hm, I would check your other search filters then. I'm not able to reproduce what you're seeing on my end unfortunately.
