### ISSUE TITLE
I am wondering if you could make it so we can choose how fast we want the Follow Play by Play to be, because it’s currently too fast to read what it says happens on each play and I like to read what it says happens on each play?

### ISSUE THREAD

**Issue by CuddlyV77** [akeaswaran/cfc-bugs#185]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by akeaswaran** [comment]
Thanks for this idea; I'll add it in a future update.
