### ISSUE TITLE
Road to Glory

### ISSUE THREAD

**Issue by IAmOne420** [akeaswaran/cfc-bugs#186]
I absolutely love the game but one feature i would love to see is like Road to Glory or Road to Heisman that way you can control the career of one specific player

**Comment by akeaswaran** [comment]
The name of the game is "College Football Coach" -- a player-driven mode would have to be an entirely different game. My focus is on completing my roadmap for this game and making it the best that it can be, and as such, I do not plan on working on other games. Sorry.
