### ISSUE TITLE
Pro/Rel Teams not being exchanged

### ISSUE THREAD

**Issue by SamT4040** [akeaswaran/cfc-bugs#187]
Please fill out the template below to make sure I can assist you most effectively.

The teams did not promote and relegate and end of season. 

**To Reproduce**
Im unsure of why this happened. All i did was finish the first season and the teams didnt switch conferences. 

**iOS version**: 14.4
**CFC version**: Newest Update
**iOS device* Iphone 12
**Jailbroken**: no
**Save File Config**: The configuration you have enabled in your save file.
- Mode (Career
- Difficulty Hard)
- Manage Coaching Staff (On
- Promotion/Relegation (On
- Automated Recruiting Off)

**Reproducible:** Unsure

**Expected behavior**

**Screenshots**
If possible, add screenshots to help show the problem.

**Video**
If possible, attach a video to help show the problem. You can attach a video by uploading it to Streamable, Gfycat, YouTube, etc. and pasting the URL here.

**Additional context**

**Comment by akeaswaran** [comment]
By chance, did you rename all of the conferences when you started your save file? Another person reported this as an issue, and I've fixed it in a future update.

**Comment by SamT4040** [comment]
Yes actually. I just realized that was the issue when I did it again.

**Comment by akeaswaran** [comment]
Cool, a fix for this will be in a future update, so I'll close this ticket. Thanks for reporting this!
