### ISSUE TITLE
I will like for player to be able you customize players in the game for example player names number and also what high school they came from

### ISSUE THREAD

**Issue by Tylet123** [akeaswaran/cfc-bugs#19]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by akeaswaran** [comment]
I am considering player name customization for a future release (but no promises on if/when this'll happen).

I understand the aesthetic reasons for having a player's number in the game, and I'm considering adding that in a future release (again, no promises), but I don't necessarily see the need for a high school name, especially now that hometowns are attached to player profiles. I'm open to feedback though, so you have a good reason for adding high schools, let me know here and we can discuss it!

**Comment by akeaswaran** [comment]
Closed with no response for three weeks.
