### ISSUE TITLE
Please provide a descriptive title here, then fill out the rest of the template.

### ISSUE THREAD

**Issue by ayaya12345** [akeaswaran/cfc-bugs#190]
Please fill out the template below to make sure I can assist you most effectively.

Coach Customization DOES NOT work
After customizing your coach, it resets to the generated data for it when you start the save.

**To Reproduce**
1. Create a new Save
2. Customize ANY part of your coach.
3. Hit 'Next' and it will reset customization for the new save.

**iOS version**: 15.0.0
**CFC version**: 5.1.1
**iOS device**: iPhone XS Max
**Jailbroken**: NO
**Save File Config**: 5.1.1
- Mode Career
- Difficulty Easy
- Manage Coaching Staff Yes
- Promotion/Relegation No
- Automated Recruiting No

**Reproducible:** Can you reproduce it every time? Or is it random?

**Expected behavior**
it should actually save the customizable features of the  #coach

**Screenshots**
If possible, add screenshots to help show the problem.

**Video**
If possible, attach a video to help show the problem. You can attach a video by uploading it to Streamable, Gfycat, YouTube, etc. and pasting the URL here.

**Additional context**

**Comment by akeaswaran** [comment]
This issue was mostly fixed in 5.1.3. Please update if you have not already.
