### ISSUE TITLE
More Position Coaches 

### ISSUE THREAD

**Issue by CoachPrime2021** [akeaswaran/cfc-bugs#192]
Hello I’ve been wondering if there is a possibility of adding more position coaches to the game like Special Teams, Offensive and Defensive Line because it would be a great challenge at hiring the best coaches to win championships ? I think it would be great for the users.

**Comment by akeaswaran** [comment]
I'm not looking to expand the coaching staff offered in the game -- I've already seen some issues with coach hiring and firing that I would like to avoid exacerbating. Sorry.
