### ISSUE TITLE
Firing & hiring coordinators, play by play speed 

### ISSUE THREAD

**Issue by CuddlyV77** [akeaswaran/cfc-bugs#194]
It would be nice if we could fire and hire offensive and defensive coordinators during the regular and off season, instead of just the off season.

It would be nice if we could choose the speed of the play by play.

Please can you possibly add the two above ideas to College Football Coach?

**Comment by akeaswaran** [comment]
I'm not looking at allowing hiring and firing during the season. That change could have unintended consequences that could affect other in-game systems.

The speed of gameplay while calling plays is dependent on how fast users are at making playcall decisions; it's not really something that can be configured. However, if you're just watching the play-by-play via the "Follow Play-by-Play" option, an option called "Gamecast Delay" was just added to the settings panel to configure how fast plays are simmed.
