### ISSUE TITLE
Players disappear if you filter recruits or transfers

### ISSUE THREAD

**Issue by 22goforit** [akeaswaran/cfc-bugs#195]
Please fill out the template below to make sure I can assist you most effectively.

**Describe the bug**
whenever I make any change to the filtering options for off season recruiting or transfers, all the offensive players and kickers all disappear. If you exit the “go to off-season” screen and go then re enter the off-season screen going back to the recruiting or transfers tab, the offensive players and kickers all show up again but this error reproduces every time you filter the players. 

**To Reproduce**
1. Go to off-season
2. Click on either recruiting or transfers
3. Select option to filter
4. Change any filtering option

**iOS version**: 15.0.1
**CFC version**: 5.1.4
**iOS device**: IPhone 8
**Jailbroken**: Not jailbroken
**Save File Config**: The configuration you have enabled in your save file.
- Mode (Career
- Difficulty (Hard)
- Manage Coaching Staff (On)
- Promotion/Relegation (Off)
- Automated Recruiting (Off)

**Reproducible:**
Yes. Every time. 

**Expected behavior**
that the offense players available would appear.

**Comment by akeaswaran** [comment]
This typically is not a bug -- it's generally due to not configuring archetypes for the selected positions. Make sure you have offensive archetypes selected and offensive players should show up. If you still don't see them show up, please let me know and I will take a look.
