### ISSUE TITLE
Carries split

### ISSUE THREAD

**Issue by bmarqs** [akeaswaran/cfc-bugs#196]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [ It’s simply odd when my 70 overall RB is getting 29 carry’s in a game and my QB has none an entire year.]

**Describe the solution you'd like**
[I’d like running backs to be given less carry’s overall unless of course the concept is smash mouth, the backup running back to get 2-3 carry’s a game, and the qb to scramble sometimes especially if they fit dual threat or scrambler.

**Comment by akeaswaran** [comment]
I think this problem could be solved by picking a different playbook -- if you use any playbook other than West Coast or Smashmouth, your QB will begin to get carries, and their rate of carries will depend on which of the other playbooks you choose. 

> the backup running back to get 2-3 carry’s a game

This will not happen unless you're using Smashmouth, which has two starting RBs anyway. The game has no concept of substitutions, so the default starters will accumulate the vast majority of statistics unless you rotate players in between games.
