### ISSUE TITLE
Coach bug

### ISSUE THREAD

**Issue by teryakibeef** [akeaswaran/cfc-bugs#197]
Please fill out the template below to make sure I can assist you most effectively.

**Describe the bug**
Whenever I choose the type or archetype of the coach I select, it doesn’t go to that archetype. It happens when you create your coach

**To Reproduce**

**iOS version**: Newest one
**CFC version**: 5.1.4
**iOS device**: IPhone Se
**Jailbroken**: Not jail broken
**Save File Config**: The configuration you have enabled in your save file.
- Mode: Career
- Difficulty: Easy
- Manage Coaching Staff: On
- Promotion/Relegation: Off
- Automated Recruiting: Off

**Reproducible:** Can you reproduce it every time? Or is it random? It happens every time

**Expected behavior**
For example when I choose defensive guru type I expect to get defensive guru

**Screenshots**
If possible, add screenshots to help show the problem.

**Video**

**Additional context**

**Comment by akeaswaran** [comment]
I think some changes in 5.1.5 (in development now) should alleviate this. Thanks for letting me know about this.
