### ISSUE TITLE
Please fix losing to bad teams

### ISSUE THREAD

**Issue by JJguy77** [akeaswaran/cfc-bugs#198]
Please fill out the template below to make sure I can assist you most effectively.

**Describe the bug**
A clear and concise description of what the bug is.  It isn’t necessarily a bug but I have a huge chance to win a game and lose.

**To Reproduce**

**iOS version**: Version of iOS this bug occurred on (can be found in Settings.app > General)
**CFC version**: Version of CFC this bug occurred on (can be found in CFC's My Team/Career tab > Gear icon > scroll to the bottom)
**iOS device**: For example iPhone XS, iPad mini, etc.
**Jailbroken**: Whether or not your device is jailbroken
**Save File Config**: The configuration you have enabled in your save file.
- Mode (Career or School/Normal)
- Difficulty (Easy or Hard)
- Manage Coaching Staff (On or Off)
- Promotion/Relegation (On or Off)
- Automated Recruiting (On or Off)

**Reproducible:** Can you reproduce it every time? Or is it random? Random

**Expected behavior**
A clear and concise description of what you expected to happen. I expected to win because it showed I would probably win by 20 points. I wish I could just win if it says I would win by 20 points.

**Screenshots**
If possible, add screenshots to help show the problem.

**Video**
If possible, attach a video to help show the problem. You can attach a video by uploading it to Streamable, Gfycat, YouTube, etc. and pasting the URL here.

**Additional context**

**Comment by akeaswaran** [comment]
This isn't a bug or an issue; this happens in real life too. A high probability of victory doesn't _guarantee_ victory -- even if you have an 80% chance to win a game, there's still a 20% chance you lose. This is just how probability works in general, and the game itself is built around probability to mimic outcomes in IRL football.
