### ISSUE TITLE
I’m season recruiting is disable on all new game saves 

### ISSUE THREAD

**Issue by brandonjmetz5** [akeaswaran/cfc-bugs#199]
Please fill out the template below to make sure I can assist you most effectively.

**Describe the bug**
When you start a new game save you cannot use in season recruiting. Just shows team search in that spot. I saw a bug on Reddit about this and when I went to start a new game I had the same issue. In setting under configuration, it states that in season recruiting is disabled. I can’t play without it due to the fact that I get 2 maybe 3 recruits per year without in season recruiting. Also I would like to mention. In post season recruiting after advancing to week two of recruiting, none and I mean absolutely zero recruits have made a decision to accept offer or deny offer so I have zero chance to flip. This means that once I push continue to finish recruiting, then I find out the decision, no flipping no changing their minds. 
**To Reproduce**
1. Go to 'new game'
2. Click on 'start game'
3. Scroll down to 'setting > configuration'

**iOS version**: Version of iOS this bug occurred on (can be found in Settings.app > General)
**CFC version**: Version of CFC this bug occurred on (can be found in CFC's My Team/Career tab > Gear icon > scroll to the bottom)
**iOS device**: For example iPhone XS, iPad mini, etc. iPhone 
**Jailbroken**: Whether or not your device is jailbroken no 
**Save File Config**: The configuration you have enabled in your save file.
- Mode (Career or School/Normal) career
- Difficulty (Easy or Hard) easy 
- Manage Coaching Staff (On or Off) off
- Promotion/Relegation (On or Off) off
- Automated Recruiting (On or Off) no option to change 

**Reproducible:** Can you reproduce it every time? Or is it random? Yes everytime 

**Expected behavior** 
Just add option to turn it off and on 
**Screenshots**
If possible, add screenshots to help show the problem.

**Video**
If possible, attach a video to help show the problem. You can attach a video by uploading it to Streamable, Gfycat, YouTube, etc. and pasting the URL here.

**Additional context**
Thanks so much. Literally have been playing this game since 2018 ish and is the longest I have ever had a game installed. Appreciate all you do. Just amazing

**Comment by akeaswaran** [comment]
The option to start new save files with in-season recruiting was disabled in 5.1 primarily due crashing issues that are a result of data storage overhead created by the mode. Existing save files that already had the feature enabled can continue to use it, but further creation has been stopped for now.

I'm not able to reproduce the situation you describe in a couple of test save files I have available. I'm guessing this is just a random occurrence and you'll have better results in future seasons. However, I'll take a look at the underlying code just to be sure.
