### ISSUE TITLE
Play by play and play calling bug

### ISSUE THREAD

**Issue by msm330** [akeaswaran/cfc-bugs#2]
I can’t use the play call or play by play option in college football coach. I tried to change it in settings but my settings won’t change.

**To Reproduce**

**iOS version**: Version of iOS this bug occurred on (can be found in Settings.app > General)
**CFC version**: Version of Apollo this bug occurred on (can be found in CFC's My Team/Career tab > Gear icon > scroll to the bottom)
**iOS device**: For example iPhone XS, iPad mini, etc.
**Jailbroken**: Whether or not your device is jailbroken
**Reproducible:** Can you reproduce it every time? Or is it random?

**Expected behavior**

**Screenshots**
If possible, add screenshots to help show the problem.

**Video**
If possible, attach a video to help show the problem. You can attach a video by uploading it to Streamable, Gfycat, YouTube, etc. and pasting the URL here.

**Additional context**

**Comment by akeaswaran** [comment]
Please fill out the template and provide more information about what you're experiencing. Are you referring to device settings or game settings? What device are you on? Do you have Display Zoom enabled?

**Comment by akeaswaran** [comment]
Update: after further review, this looks to be a similar situation to #4.
