### ISSUE TITLE
Coaching Hiring and Firing

### ISSUE THREAD

**Issue by Firewarrior7143** [akeaswaran/cfc-bugs#20]
So, I’m a control freak.  I want my offense to run my systems, but I want to hire a coach that is in tune with my systems.  For instance, I run west coast offense with a 3-3-5 defense...

I want to hire a coach that has about the same philosophy as I do.  The chances of making it work are greater as a result. 

I play this for the AD/scouting aspect.  I do enjoy it!  And I hope for more bells and whistles in the future!

**Comment by akeaswaran** [comment]
I'm considering this for a future release -- thanks for the suggestion!
