### ISSUE TITLE
Home/Away Listing of Teams

### ISSUE THREAD

**Issue by dcagle8** [akeaswaran/cfc-bugs#200]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by dcagle8** [comment]
I noticed that in the schedule and gameplay scoreboard that the home team is listed on top. Is there any way that the away team could be on top instead, to be consistent with typical ESPN, CBS, and other sports sites? I really appreciate all that has been done to help make this app as great as it is!

**Comment by akeaswaran** [comment]
I'm not sure what you mean; in all places where games are displayed, the away team is already always listed first/on the top. Can you please provide a screenshot of where you're seeing the home team listed first?

**Comment by akeaswaran** [comment]
Closing without response.
