### ISSUE TITLE
Interviews and harder difficulty 

### ISSUE THREAD

**Issue by Eryk-ops** [akeaswaran/cfc-bugs#201]
**Is your feature request related to a problem? Please describe.**
I love the game but after playing for a couple of seasons it just feels bland
**Describe the solution you'd like**
If your team sucks or just isn’t a good school it should be a lot harder to get quality players. I wish there was a way to make it so acedamics play a roll in signing a player. Like you could make it so we can upgrade the school/ classrooms or make it making a high quality locker room but it requires points. Also wish there was maybe a social media tab so you could hype up the fans. And another thing maybe is to get fans and there may be a tab for seeing how many fans your team has. Also there should be televised games that you could try to get like in ncaa 14. 
**Describe alternatives you've considered**
I know you guys arnt a triple a studio and I love the game but I feel like it should have a major update soon to be the new retro bowl in popularity 
**Additional context**

**Comment by akeaswaran** [comment]
The roadmap has some refinements for school mode that include exchanging offseason points for program improvements (locker room, football operations, etc) that would be tied into recruiting (usual caveats about this statement not being a promise that this feature will 100% appear in the game apply).

If you find the game easy, even on hard mode, I generally consider that a point where you have beaten the game. There's not really much harder I plan to make the game -- there's been about equal feedback at both extremes on game difficulty, which seems to indicate to me that difficulty is really just about in the right place.

> I know you guys arnt a triple a studio and I love the game but I feel like it should have a major update soon to be the new retro bowl in popularity

There was just a major update about two months ago. You're right -- I am not a AAA game studio, nor am I multiple people. I work on updates when I have free time, so I'm not beholden to a specific release timeline that competes with other games. I'm just focused on making this one the best it can be by completing the roadmap the community and I built together.
