### ISSUE TITLE
Clock management and Ai play making 

### ISSUE THREAD

**Issue by Outzabast** [akeaswaran/cfc-bugs#203]
**Is your feature request related to a problem? Please describe.**
In close games in the 4th quarter there is no way to handle clock management
E.g in a conference championship game the last play was snapped with 27 seconds left, it’s an incomplete pass which ought to stop the clock. There being no clock management means that despite there being 27 seconds left the play, the play menu doesn’t allow for a coach to call for a spike ball or for the games time management to call for a clock stoppage on an incomplete pass. 

**Describe the solution you'd like**
A good two pronged solution for on any incomplete pass for the clock to remain the same between the end of that play and the next allowing for a subtraction of time in which the play occurred. I.e a pass play with 15:00 left in the first quarter takes 8 seconds and results in an incomplete pass meaning that at the snap of the next play there should be 14:52 left in the first. 

Also if a run play is performed with 15:00 left in the first the game could account for clock run off between snaps. I.e if the ball is run from the 20 to the 25 (not a first down) therefore the clock would run between the snaps. Therefore, despite the play being only 5 seconds from snap to runner being down, to respot the ball and subs the clock run off would be ~15-20 secs 

I figured not seeing any of the code this would be a relatively “simple” step to implement that would add to the immersion of this great app. It might be good to add a “hurry up” and “chew clock” coach mentality to both AI play selection and user that would allow for better decision making in game.

**Comment by akeaswaran** [comment]
Thanks for the suggestions here! I'll see if I can incorporate some of these into a future update.

> It might be good to add a “hurry up” and “chew clock” coach mentality to both AI play selection and user that would allow for better decision making in game.

A "tempo" option like you describe here is available in the iPhone version of the app -- if you're on iPad, you will not see this  due to some technical constraints. I'm aiming to make this available on iPad in a future update.
