### ISSUE TITLE
New feature

### ISSUE THREAD

**Issue by philipdukeqb08** [akeaswaran/cfc-bugs#204]
**Is your feature request related to a problem? Please describe.**
Be able to start as an offensive or defensive coordinator and work your way to being a head coach 
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by akeaswaran** [comment]
After supporting sending head coaches back to coordinator jobs caused widespread issues for months, I am reluctant to mess with now-working coach hiring/firing code. I will not be working on this. Sorry.
