### ISSUE TITLE
You should add the choice to make/change what teams are in each conference. Allowing people to make super conferences!

### ISSUE THREAD

**Issue by Micah957** [akeaswaran/cfc-bugs#208]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by akeaswaran** [comment]
One can already customize team information via metadata file. Unfortunately, the number of teams in a conference can not change -- more than 10 teams in a conference would require added complexity in the scheduling algorithm, and it would require overhauling a lot of underpinnings inside save files.
