### ISSUE TITLE
Option to Start New Save In The Off Season/Option to Cut Players From Team

### ISSUE THREAD

**Issue by 1CoachV** [akeaswaran/cfc-bugs#209]
It would be nice when starting a new save if we had the ability to start the season during the off season to further improve the personalisation of the game by having the opportunity to recruit players that suits the style of how we would like to play the game instead of waiting to get 1 season in before having the chance to do so.

Also cutting players from the team would also be nice addition. Lets say if you recruited a bunch of guys but a couple of the players overall is not up to par you can release/cut them from the team and have them placed in transfer market of the next off season.

**Comment by akeaswaran** [comment]
Cutting players is under consideration for a future release (note: this is not a promise that this feature will appear in the game; it's just a promise that I will look into it).

Starting a save file in an offseason is probably not going to happen based on limitations in how the game engine is set up. Sorry.
