### ISSUE TITLE
Coordinator Update Suggestion

### ISSUE THREAD

**Issue by ImNotSmartSoICantThinkOfAUserName** [akeaswaran/cfc-bugs#213]
First idea: I think it would be cool if there was a coordinator extension update where we could start out as a coordinator, where you only recruit for yourside of the ball (O / D), then develop a good team and get HC offers (Make both HC & coordinator choices available to start out with, but just an option). Addition to that, it would be cool if once we’re a HC, we can see our OC/DC’s get HC offers after a couple of years of being good, and they develop programs of their own

Second idea: I think it would be cool if over time as a program gets good / better, you could update you update you facilities which would attract recruits to come to your program

just some idea’s i’ve thought of as I played the game, I think it would be fun.

**Comment by akeaswaran** [comment]
> I think it would be cool if there was a coordinator extension update where we could start out as a coordinator, where you only recruit for yourside of the ball (O / D), then develop a good team and get HC offers (Make both HC & coordinator choices available to start out with, but just an option).

This was originally planned for a release, but had to be cut due to issues with coordinator hiring. Sorry.

> Addition to that, it would be cool if once we’re a HC, we can see our OC/DC’s get HC offers after a couple of years of being good, and they develop programs of their own

This is already supported.

> Second idea: I think it would be cool if over time as a program gets good / better, you could update you update you facilities which would attract recruits to come to your program

This is planned for a future release.

Thanks for the feedback!
