### ISSUE TITLE
Player health and fatigue / subs

### ISSUE THREAD

**Issue by GamingDad29** [akeaswaran/cfc-bugs#214]
**Hi, first off, thank you for this great game! It’s like playing NCAA football without all the flash and load screens that some of us just want to get through to get to the Dynasty modes.

**Describe the solution you'd like**
From what I’ve seen so far, it might be kind of nice to be able to make substitutions during the games. Also, if there was some way to incorporate a fatigue factor for players in the games might be neat. 

Lastly, player injuries would also spice things up a bit for the common football strategist.

**Describe alternatives you've considered**

You’ve definitely made the game challenging with the small amount of Coach points to use for hiring coaches, recruiting, transfers, etc. having those points more clearly portrayed would be a big help.

**Additional context**

Again, thank you for your efforts as this game is very enjoyable, I just wanted to throw my 10 cents out there for some suggestions. Have a great day!

**Comment by akeaswaran** [comment]
Thanks for the feedback! Let me reply to each of your points separately:

> From what I’ve seen so far, it might be kind of nice to be able to make substitutions during the games. Also, if there was some way to incorporate a fatigue factor for players in the games might be neat.

Unfortunately, I'm not planning on supporting substitutions. I realize that this makes the game a little unrealistic, but my goal is to keep the game fairly simple. I laid out the guiding principles for the game's design [here](https://www.reddit.com/r/FootballCoach/comments/cgkyna/cfc_40_update/), and I actually mentioned in-game substitutions as something that breaks one of those principles. Hope this makes sense!

> Lastly, player injuries would also spice things up a bit for the common football strategist.

This is actually already supported in the game's Hard difficulty!

> You’ve definitely made the game challenging with the small amount of Coach points to use for hiring coaches, recruiting, transfers, etc. having those points more clearly portrayed would be a big help.

I've added more visibility of that number in a future release -- thanks for pointing this out!
