### ISSUE TITLE
Please provide a descriptive title here, then fill out the rest of the template.

### ISSUE THREAD

**Issue by BronzeChant** [akeaswaran/cfc-bugs#215]
Please fill out the template below to make sure I can assist you most effectively.

**Describe the bug**
2 Problems. Im on school mode and im 20 seasons in. Coaches Stats are not staying in the statistics, maybe they never did but i thought they did. Plus coaches that go to your team disappear if they leave your team no matter how old they are. Is this supposed to happen?  Also there was coaches in their 70s from other teams that shouldve been in the Hof yet they arent on teams or in the Hof.  Is this normal? 

**To Reproduce**

**iOS version**: Version of iOS this bug occurred on (can be found in Settings.app > General)
**CFC version**: Version of CFC this bug occurred on (can be found in CFC's My Team/Career tab > Gear icon > scroll to the bottom)
**iOS device**: For example iPhone XS, iPad mini, etc.
**Jailbroken**: Whether or not your device is jailbroken
**Save File Config**: The configuration you have enabled in your save file.
- Mode (Career or School/Normal)
- Difficulty (Easy or Hard)
- Manage Coaching Staff (On or Off)
- Promotion/Relegation (On or Off)
- Automated Recruiting (On or Off)

**Reproducible:** Can you reproduce it every time? Or is it random?

**Expected behavior**

**Screenshots**
If possible, add screenshots to help show the problem.

**Video**
If possible, attach a video to help show the problem. You can attach a video by uploading it to Streamable, Gfycat, YouTube, etc. and pasting the URL here.

**Additional context**

**Comment by akeaswaran** [comment]
Can you please be a little clearer in your descriptions of these issues? A few screenshots and completion of the issue template above will help as well. Thanks!

**Comment by akeaswaran** [comment]
Closing with no response.
