### ISSUE TITLE
Can’t customize coach when starting new save file

### ISSUE THREAD

**Issue by gwsavage** [akeaswaran/cfc-bugs#216]
When I start a new save file and a new season I am not allowed to customize my coach. It skips the screen where you can name the coach and choose their attributes. I have updated the game. I have deleted and restarted reinstalled it and I continue to get that bug. I play on my iPhone.

**Comment by akeaswaran** [comment]
You need to pick Career mode in order to customize your coach. That option is not available at the start of a School Mode save file.
