### ISSUE TITLE
Some type of player career mode it might be tough but man I would never stop playing if there was some type of player career mode

### ISSUE THREAD

**Issue by Tkret190** [akeaswaran/cfc-bugs#217]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by akeaswaran** [comment]
I'm not considering this feature for a future release. The game is named "College Football _Coach_", so any player career mode would be a completely different game.

Sorry.
