### ISSUE TITLE
more teams, or players transferring to your team without having to pay for them 

### ISSUE THREAD

**Issue by nolyn1** [akeaswaran/cfc-bugs#219]
I feel like transferring is a good idea and great part of this game. But i and other people as well feel like transfers can come to your school without spending recruiting points on them. like if your a small school and there was a talented prospect like for example take tate martel  was a 5 star out oh highschool and went to miami then transfers to ucla and after that he transfers to unlv a small school where he can get play time so i think that small schools should revive transfers that were bust coming out oh highschool and the big schools should get players from small teams putting up great numbers and wanting to move on to a power 5 conference for more professional scouts etc… This would be a great feature into the game it’s like ncaa 14 that’s where i have got this idea from because i love that game and play it very often and i think it’d make much more sense for those things to happen and if you don’t want the transfers then you can decline them or accept them. And for the more teams part of this i had an idea of like an fcs type of thing but you wouldn’t call it that ofc but you could like you can choose to play fcs and when you get good enough there you take your team to the fbs and add a whole new different style of gameplay through another lower league but once you get good enough you should be able to have a opportunity to make your team a fbs school into a group of 5 team and then work up to a power 5 that would be a cooool idea that players like me that want the full college experience would love, thank you for your time and reading this and this is what i think would make the game so much better and entertaining <3

**Comment by akeaswaran** [comment]
Re: transfers -- I understand where you're coming from, but there are two issues I have with implementing this:

1. There needs to be some concept of scarcity or risk when a user takes an action in the game. Everything a coach does IRL is zero-sum -- it's something that is taking time or effort away from something or someone else. Having a cost for transfer recruitment mimics this real-life constraint.
2. Transfers are courted by college football programs; they don't apply and get accepted/rejected from a target school. That's just not how the system works (unless the transfer is walking-on at the next school, but that is an edge case). Again, the current in-game system mimics this IRL constraint.

Re: adding more teams -- I have no plans to add more teams, but your desire to move teams to higher and higher conferences is covered by the integration of vertical promotion/relegation in version 5.1.6.

Thanks for the feedback!
