### ISSUE TITLE
No not related to a problem but you can make recruiting a season long thing instead of just the offseason because you can Taylor needs to a specific recruiting class and also add attributes which might be easier said than done but that would make the game soo good just mainly creating another layer of depth into the game mainly since it’s just a franchise and the gameplay aspect is not very deep because both can’t be surface level but having at least one of the aspects of the game has to keep me coming back to the game  

### ISSUE THREAD

**Issue by Hungabunga** [akeaswaran/cfc-bugs#220]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by akeaswaran** [comment]
In-season recruiting is already supported -- make sure you're on the latest version from the App Store and scroll all the way down on the save file configuration screen when creating a new save file. 

I'm not really sure what you mean by `attributes` -- all players/coaches have different ratings and proficiencies that are viewable in game. If you're talking about upgradable components of a specific program, that is a feature being considered for a future release.
