### ISSUE TITLE
Please provide a descriptive title here, then fill out the rest of the template.

### ISSUE THREAD

**Issue by jones350** [akeaswaran/cfc-bugs#222]
Please fill out the template below to make sure I can assist you most effectively.

The game does not record all of my defensive stats. For example my LB will get several PD’s but when looking at the stat board after the game it shows nil. Same with tackles as well, my team should receive more than 40 tackles for the way i play the game but the stats only show a combined 9 tackles among all my players
**To Reproduce**
1. Play a game
2. Record manually your tkl, int, etc count
3. Finish game
4. See error(the missing stats)

**iOS version**: Version of iOS this bug occurred on (can be found in Settings.app > General)
**CFC version**: Version of CFC this bug occurred on (can be found in CFC's My Team/Career tab > Gear icon > scroll to the bottom)
**iOS device**: For example iPhone XS, iPad mini, etc.
**Jailbroken**: Whether or not your device is jailbroken
**Save File Config**: The configuration you have enabled in your save file.
- Mode (Career or School/Normal)
- Difficulty (Easy or Hard)
- Manage Coaching Staff (On or Off)
- Promotion/Relegation (On or Off)
- Automated Recruiting (On or Off)

**Reproducible:** Can you reproduce it every time? Or is it random?

**Expected behavior**

**Screenshots**
If possible, add screenshots to help show the problem.

**Video**
If possible, attach a video to help show the problem. You can attach a video by uploading it to Streamable, Gfycat, YouTube, etc. and pasting the URL here.

**Additional context**

**Comment by akeaswaran** [comment]
How are you counting tackles? The players that make tackles are not exposed in play-by-play logs, and the game generally tries to track the rate of plays that end in a tackle vs those that end out-of-bounds with IRL tackle rates. 

As for INTs, I'm not seeing anything in the code that would indicate an inconsistency with box score stats and I haven't been able to reproduce what you're seeing either. 

For passes defended, there _does_ seem to be an inconsistency with how these are reported, so I'll patch that in a future release. Thanks for letting me know about this!
