### ISSUE TITLE
It would be cool if you played a team for so many years consecutively it automatically starts a rivalry or when you get blown out that team becomes a potential rival 

### ISSUE THREAD

**Issue by Jamosg** [akeaswaran/cfc-bugs#223]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by akeaswaran** [comment]
I think these would best be manually configured, which is already supported in-game. During any offseason (IE: after the national championship game has been played), head to the Career/My Team tab (depending on the mode of your save file) and tap the Team Streaks option. From here, as long as you’ve played a team at least once, you’ll see them listed. Scroll through the list to find the team that you want to add/remove from your list of rivalries and swipe right to left on their row in the list to see relevant options appear.

**Comment by Jamosg** [comment]
Thank you
