### ISSUE TITLE
Edit Attributes

### ISSUE THREAD

**Issue by rehmmmm** [akeaswaran/cfc-bugs#225]
I wish you could edit a players attributes. It would be awesome if I could edit a players attribute like instead of being a 60 overall in speed i could change it to like 90 for example. I think a lot of other users would also enjoy the feature.

**Comment by akeaswaran** [comment]
This is already supported via metadata file customization. I don't intend to support this in-game for game balance purposes. Sorry.

**Comment by rehmmmm** [comment]
Can you send me the link of the customization file?

**Comment by akeaswaran** [comment]
I don't maintain or manage any metadata files. You can use [subreddit search](https://www.reddit.com/r/FootballCoach/search?q=metadata&restrict_sr=on) to find valid files on the [/r/FootballCoach forum](https://reddit.com/r/FootballCoach) on Reddit.com, though.
