### ISSUE TITLE
Expanded CFP Options/Voting

### ISSUE THREAD

**Issue by WRuth19** [akeaswaran/cfc-bugs#227]
Hello,

First and foremost I just wanted to say that I downloaded the game a few days ago and am in love with it. It is so fun to play! Additionally, the football knowledge included in the game is so cool! Football lovers will definitely tell that the developer of the game knows their stuff when it comes to the gridiron! Anyways I was just wondering if it is at all possible for the addition of Expanded CFP Options/Voting like there is the option for relegating. 

Thank you,

Will

**Comment by akeaswaran** [comment]
My stance on this has been that if/when the CFP officially expands, I will mirror that in the game. So far, all expansion talks have been hypothetical at best, so I've not planned any changes here just yet.
