### ISSUE TITLE
Custom Promotion/Relegation

### ISSUE THREAD

**Issue by JamesJacks53** [akeaswaran/cfc-bugs#228]
**Is your feature request related to a problem? Please describe.**
No, just a frustrating line up between conferences

**Describe the solution you'd like**
The ability to customize which conferences are paired up for promotion and relegation. Example - right now with promotion/relegation enabled, Pacific teams are always relegated to the East. It would be nice to be able to set up a career so that the Pacific is paired with the Northwest; Lakes with Mid-Atlantic, etc. 

**Describe alternatives you've considered**
Rebranding every team and conference so it lines up with a logical geographic promotion/relegation. Alternatively, the ability to set which teams are in certain conferences at the beginning of a career set up, and then just renaming the conferences. 

**Additional context**
It could be a simple drop down menu for the “Power 6” or a drag and drop into a matrix interface. I think it would add to the idea of promotion and relegation that I enjoy by allowing for simpler geographic alignment.

**Comment by akeaswaran** [comment]
Thanks for the feedback! This functionality is already supported in metadata files, so I'd check those out on [the subreddit](https://reddit.com/r/FootballCoach). The base implementation of pro/rel in the game was kept mostly simple for ease of feature delivery (like you mentioned, the first six conferences were entirely arbitrarily matched with the last six without regard to geography, league quality, etc) to users, and I figured interested users would explore/extend the functionality via metadata.
