### ISSUE TITLE
Add a class grade

### ISSUE THREAD

**Issue by chicagobear** [akeaswaran/cfc-bugs#23]
Just a suggestion I thought it would be a nice feature to add a grade (or average overall) for every class and the number of people in a class for every school. That way if you’re switching schools you can see how big the class is that is leaving, and how good the younger classes are. Or you could use it if your curious how good your own younger classes are and how big your senior class is without having to count them all.

**Comment by akeaswaran** [comment]
This will be in a future release. Thanks for suggesting it!
