### ISSUE TITLE
Right Endzone Rebrand

### ISSUE THREAD

**Issue by BrazzerK** [akeaswaran/cfc-bugs#230]
Please fill out the template below to make sure I can assist you most effectively.

**Describe the bug**
The rebrand option for the right endzone isn’t working correctly. I don’t receive the pop up stating the rebrand was successfully completed and the endzone doesn’t change color.

**To Reproduce**
1. Go to rebrand program
2. Click on right endzone color
3. Click pick new color
4. Click color
5. Click X
6. No notification stating “successfully completed” pops up

**iOS version**: 15.3.1
**CFC version**:
**iOS device**: iPhone XR
**Jailbroken**: device is not jailbroken
**Save File Config**: The configuration you have enabled in your save file.
- Mode Career
- Difficulty (Hard)
- Manage Coaching Staff (On)
- Promotion/Relegation (Off)
- Automated Recruiting (Off)

**Reproducible:** yes it’s reproducible 

**Expected behavior**
To have the endzone change color

**Additional context**

**Comment by akeaswaran** [comment]
This should be fixed with 5.1.9. Sorry for the inconvenience!
