### ISSUE TITLE
Season Settings

### ISSUE THREAD

**Issue by nahdeucewylin** [akeaswaran/cfc-bugs#232]
**Is your feature request related to a problem? Please describe.*
it’s not a problem i just wish to be able to change certain settings after already starting the franchise. Things such as whether or not i want to manage my staff or recruit during the season.

Idk if there is a way to do so, and if there is then i apologize in advance for my stupidity lol.

**Additional context**

**Comment by akeaswaran** [comment]
This will not be supported -- sorry. Allowing changes to those settings mid-season could corrupt data.
