### ISSUE TITLE
Ability to change to any jersey number, randomize if it is already taken 

### ISSUE THREAD

**Issue by AlzawadT** [akeaswaran/cfc-bugs#237]
Please fill out the template below to make sure I can assist you most effectively.

**Describe the bug**
When selecting a players jersey number, we should be able to select any jersey number. Randomize who currently has that jersey number if selected. 

**To Reproduce**
1. Go to a selected player 
2. Click on edit 
3. Scroll down to change jersey number and edit number 

**iOS version**: Version of iOS this bug occurred on (can be found in Settings.app > General)
**CFC version**: Version of CFC this bug occurred on (can be found in CFC's My Team/Career tab > Gear icon > scroll to the bottom)
**iOS device**: For example iPhone XS, iPad mini, etc.
**Jailbroken**: Whether or not your device is jailbroken
**Save File Config**: The configuration you have enabled in your save file.
- Mode (Career or School/Normal)
- Difficulty (Easy or Hard)
- Manage Coaching Staff (On or Off)
- Promotion/Relegation (On or Off)
- Automated Recruiting (On or Off)

**Reproducible:** Can you reproduce it every time? Or is it random?

**Expected behavior**

**Screenshots**
If possible, add screenshots to help show the problem.

**Video**
If possible, attach a video to help show the problem. You can attach a video by uploading it to Streamable, Gfycat, YouTube, etc. and pasting the URL here.

**Additional context**

**Comment by akeaswaran** [comment]
The central problem here is not a bug: you're able to change a player's uniform number at any time, but you're limited by the NCAA regulation numbers (see: https://en.wikipedia.org/wiki/Uniform_number_(American_football)#NCAA).

I can look into adding a number randomizer in the future though -- thanks for the suggestion!
