### ISSUE TITLE
RB By Committee

### ISSUE THREAD

**Issue by frat-sadford** [akeaswaran/cfc-bugs#24]
**Is your feature request related to a problem? Please describe.**
Would it be possible to use multiple backs using playbooks besides Smashmouth?

**Describe the solution you'd like**
A way to spread carries among a couple RBs using other playbooks, such as the Run-Pass Option playbook. I'm not sure how complicated to add this would be because it would mean more than 11 offensive players would be involved in the game.

**Describe alternatives you've considered**

**Additional context**

**Comment by akeaswaran** [comment]
No, this wouldn't really be possible in the current format of the game -- a starter at another position (WR or TE) would have to be removed to add another RB to the rotation, and doing that would negate the bonuses of other playbooks like the spread or the west coast.
