### ISSUE TITLE
Grad Transfer Stats

### ISSUE THREAD

**Issue by frat-sadford** [akeaswaran/cfc-bugs#28]
**Describe the bug**
My grad transfer RB's season stats do not appear. All it shows is "This player graduated in 0.", as shown in the screenshot below. However, his career stats are updating and displayed correctly.

**To Reproduce**
1. Get a graduate transfer
2. Go to depth chart
3. Open player page, and scroll down to "Season Statistics".

**iOS version**: 13.2
**CFC version**: 4.1.4
**iOS device**: iPhone XR
**Jailbroken**: Not jailbroken
**Reproducible:** Yes

**Expected behavior**
The grad transfer RB's season stats to be displayed

**Screenshots**
![60DA3D0E-51C9-4889-BCEE-4FDDAE8759F0](https://user-images.githubusercontent.com/67602622/87054836-96c46380-c1d1-11ea-9d96-77cbea7b13aa.png)

**Additional context**
2024, American Samoa, career mode on hard difficulty

**Comment by frat-sadford** [comment]
Update: I checked several other grad transfers on other teams, and they all had the same issue

**Comment by akeaswaran** [comment]
Should have a fix for this in the next update -- thanks for reporting this!
