### ISSUE TITLE
OT Scores

### ISSUE THREAD

**Issue by frat-sadford** [akeaswaran/cfc-bugs#29]
**Describe the bug**
In the scoring summary for a game that went to 12 overtimes (between two computer teams), the scores for the tenth overtime through the twelfth overtime show up between the first overtime and the second overtime. I think it might be because the out of order overtime periods start with a "1", so they get listed before 2OT. Not sure this is really worth the time to fix, because not many games go this long, but I figured I'd report it anyway.

**To Reproduce**
1. Go to the box score for the game
2. Tap the three dots on the upper left
3. Select "view scoring summary"

**iOS version**: 13.2
**CFC version**: 4.1.5
**iOS device**: iPhone XR
**Jailbroken**: not jailbroken
**Reproducible:** Yes

**Expected behavior**
I expected the overtime scores to show up in chronological order.

**Screenshots**
![601441CC-E69B-4432-B32E-523C70DC1FAC](https://user-images.githubusercontent.com/67602622/87336064-4de11780-c50f-11ea-9384-33f2141e4330.png)
![BDBA86C6-812D-4EBD-B548-A378C9E9649C](https://user-images.githubusercontent.com/67602622/87336067-4e79ae00-c50f-11ea-894e-4645fa0f3aa0.png)
![B83BFB53-40DD-4257-9C5E-6292E64A338F](https://user-images.githubusercontent.com/67602622/87336069-4f124480-c50f-11ea-887b-444d08d68d39.png)

**Additional context**

**Comment by akeaswaran** [comment]
1. Thank you for filling out the template.
2. How did you even get a game to go this long?
3. I think I have a fix for this in a future update -- look out for this in the near future!

Thanks for reporting!

**Comment by frat-sadford** [comment]
> 2. How did you even get a game to go this long?

I didn't! I'm the coach at American Samoa in this save. These are two computer schools lmao.
