### ISSUE TITLE
Recruiting 

### ISSUE THREAD

**Issue by tharness8806** [akeaswaran/cfc-bugs#3]
When recruiting I can’t click on any of the recruits to perform the actions needed to recruit them. IOS iPhone 10x max

**Describe the bug**
A clear and concise description of what the bug i
**To Reproduce**

**iOS version**: Version of iOS this bug occurred on (can be found in Settings.app > General)
**CFC version**: Version of Apollo this bug occurred on (can be found in CFC's My Team/Career tab > Gear icon > scroll to the bottom)
**iOS device**: For example iPhone XS, iPad mini, etc.
**Jailbroken**: Whether or not your device is jailbroken
**Reproducible:** Can you reproduce it every time? Or is it random?

**Expected behavior**

**Screenshots**
If possible, add screenshots to help show the problem.

**Video**
If possible, attach a video to help show the problem. You can attach a video by uploading it to Streamable, Gfycat, YouTube, etc. and pasting the URL here.

**Additional context**

**Comment by akeaswaran** [comment]
Not a bug. If a recruit's name is grayed out and you can't view their profile, you have too low of a prestige to interact with them.
