### ISSUE TITLE
CPU auto-loses even when scoring in the bottom half of OT

### ISSUE THREAD

**Issue by FunGun12** [akeaswaran/cfc-bugs#32]
Please fill out the template below to make sure I can assist you most effectively.

**Describe the bug**
On IOS.
In the bottom of OT, if the computer scores, and kicks an extra point to tie, the game ends and they still lose.
**To Reproduce**

**iOS version**: Version of iOS this bug occurred on (can be found in Settings.app > General)
**CFC version**: Version of CFC this bug occurred on (can be found in CFC's My Team/Career tab > Gear icon > scroll to the bottom)
**iOS device**: For example iPhone XS, iPad mini, etc.
**Jailbroken**: Whether or not your device is jailbroken
**Reproducible:** Can you reproduce it every time? Or is it random?

**Expected behavior**

**Screenshots**
If possible, add screenshots to help show the problem.

**Video**
If possible, attach a video to help show the problem. You can attach a video by uploading it to Streamable, Gfycat, YouTube, etc. and pasting the URL here.

**Additional context**

**Comment by akeaswaran** [comment]
Please fill out the rest of the template if possible.

**Comment by akeaswaran** [comment]
No response for over a year, closing.
