### ISSUE TITLE
Would it be possible to make it so we could get a sandbox mode where you can change what teams are in what conferences?

### ISSUE THREAD

**Issue by MuPzz** [akeaswaran/cfc-bugs#34]
**Is your feature request related to a problem? Please describe.**
No, this was just an idea that came to me while I was playing. And I thought it would be a fun thing to play with. 

**Describe the solution you'd like**
Making a different game mode that you could choose what teams are in what conferences so that way career mode and school mode aren’t interfered with and made easier
**Describe alternatives you've considered**
You could also make it an option to enable in school mode and in career mode but I feel like it would make it too easy to cheat with challenges

**Additional context**
N/A

**Comment by akeaswaran** [comment]
Thanks for the suggestion! 

Unfortunately, I don't think this is necessary -- you can do the same customization of conference alignment with metadata files. If you're unfamiliar with those, there's a tutorial in the Game Guide, which you can access from the Settings panel.
