### ISSUE TITLE
Game won’t let me retire

### ISSUE THREAD

**Issue by Hawk7742** [akeaswaran/cfc-bugs#36]
So my coach reached age 95 and it’s time for me to retire but when I hit the retire button nothing happens. I like to keep a picture of the Career Card at the end and it’s not letting me see that card or start a new coach. This was my most successful coach so I wanted this career card most. Is there anything you can do to fix the game for me? Thank you so much

**Comment by akeaswaran** [comment]
Thanks for letting me know about this -- looks like a bug in how that menu is served. Will patch this ASAP.
