### ISSUE TITLE
Play by Plau

### ISSUE THREAD

**Issue by PlatypusKing50** [akeaswaran/cfc-bugs#4]
Every time I push the Turn on Full Play by Play in the settings it resets to where I can’t do Full Play by Play (it turns off shortly after I turn it on automatically) and the only thing I can do sim games, which kind of ruins the game.

**Describe the bug**

**To Reproduce**

**iOS version**: Version of iOS this bug occurred on (can be found in Settings.app > General)
**CFC version**: Version of Apollo this bug occurred on (can be found in CFC's My Team/Career tab > Gear icon > scroll to the bottom)
**iOS device**: For example iPhone XS, iPad mini, etc.
**Jailbroken**: Whether or not your device is jailbroken
**Reproducible:** Can you reproduce it every time? Or is it random?

**Expected behavior**

**Screenshots**
If possible, add screenshots to help show the problem.

**Video**
If possible, attach a video to help show the problem. You can attach a video by uploading it to Streamable, Gfycat, YouTube, etc. and pasting the URL here.

**Additional context**

**Comment by akeaswaran** [comment]
Please fill out the template and provide more information on how to reproduce this. What device are you on? Do you have display zoom enabled?

**Comment by akeaswaran** [comment]
Update: this looks to be a misunderstanding of what the "Full Play by Play" option in Settings means. This enables full text play-by-play logs in the game summary and does not reveal playcalling options. If you are on an unsupported device (iPhone 5/SE/5s), this will not enable playcalling for you. I will update this text to be clearer in the future.
