### ISSUE TITLE
Current coach can be reused after "selecting a new coach" in retirement options

### ISSUE THREAD

**Issue by bradlfield** [akeaswaran/cfc-bugs#42]
Please fill out the template below to make sure I can assist you most effectively.

**Describe the bug**
When you chose to retire and select a new coach
It a) let’s your old coach continue instead of staying retired and b) shows a coaching record
![395B0D40-4ABE-46F6-9097-F2B6191F838F](https://user-images.githubusercontent.com/69269601/90162387-2671aa80-dd5a-11ea-9f63-41d48e6144cc.png)

**To Reproduce**

**iOS version**: Version of iOS this bug occurred on (can be found in Settings.app > General)
**CFC version**: Version of CFC this bug occurred on (can be found in CFC's My Team/Career tab > Gear icon > scroll to the bottom)
**iOS device**: For example iPhone XS, iPad mini, etc.
**Jailbroken**: Whether or not your device is jailbroken
**Reproducible:** Can you reproduce it every time? Or is it random?

**Expected behavior**

**Screenshots**
If possible, add screenshots to help show the problem.

**Video**
If possible, attach a video to help show the problem. You can attach a video by uploading it to Streamable, Gfycat, YouTube, etc. and pasting the URL here.

**Additional context**

**Comment by akeaswaran** [comment]
This should be fixed in 4.2, rolling out this week on the App Store. Thanks for reporting!
