### ISSUE TITLE
Recruiting

### ISSUE THREAD

**Issue by Kennan2002** [akeaswaran/cfc-bugs#43]
Make the swipe action in recruiting to do all 4 option instead of individually picking one and having to swipe again 

Add defensive player of the year 

Add more popular schools like Clemson penn state Georgia etc and take the smaller school like New York upstate Murfreesboro etc and move them to a subdivision 

Add a recruiting feature where you can recruit high school players while they are still juniors sophomores and freshman and when they become seniors they show up in that recruiting class but may need to be flipped back if another school talks to them

Be able to conceive players from other programs to transfer into your program but make it legal during a certain time so it it’s possible to occur sanctions put in both modes but on easy you can do it during the entire year and offseason and can’t incur sanctions

Add team records like most offensive yards first downs team sacks 

Add special teams positions like kick and punt returner be able to put wr rb at the as the returns and have specific players just as punt or kick returner add kick return and punt return stats

Add offensive defensive and special team coordinators who add boosts to your schemes and players and can effect your teams performance both positively and negatively depending on if they fit they your schemes make the coach lvl based so the higher the level the higher the boost they give and the make hiring phase like recruiting 

Add receiving year to running backs 

Fix all league teams my 3 receivers will put 150+ rectpion 2000+ yards and 30+ tds and not make the team but a receiver with 750 yards and 8 tds will

Fix defenses where DL should get more sacks than the like back in 4-3 defense

**Comment by akeaswaran** [comment]
Thanks for the feedback -- let me try to hit your points one at a time.

> Make the swipe action in recruiting to do all 4 option instead of individually picking one and having to swipe again

This was originally how I had this built out, but it's way too easy to trigger this with a swipe. I'll see if there's a better way it can be done in a future release.

> Add defensive player of the year

Already under consideration for a future release!

> Add more popular schools like Clemson penn state Georgia etc and take the smaller school like New York upstate Murfreesboro etc and move them to a subdivision

Can't do that; I explained this in your last post here, but TL;DR -- I don't have the money to pay for licensing rights to those schools. State names are a gray area.

> Add a recruiting feature where you can recruit high school players while they are still juniors sophomores and freshman and when they become seniors they show up in that recruiting class but may need to be flipped back if another school talks to them

Eh, this would make the game pretty complicated and the recruiting would take way too long. I'm happy with how simple it is right now.

> Be able to conceive players from other programs to transfer into your program but make it legal during a certain time so it it’s possible to occur sanctions put in both modes but on easy you can do it during the entire year and offseason and can’t incur sanctions

Not happening.

> Add team records like most offensive yards first downs team sacks

This is a great idea -- will see if I can add this in a future release!

> Add special teams positions like kick and punt returner be able to put wr rb at the as the returns and have specific players just as punt or kick returner add kick return and punt return stats

You mentioned this in your previous post; again, there's not really a need for this.

> Add offensive defensive and special team coordinators who add boosts to your schemes and players and can effect your teams performance both positively and negatively depending on if they fit they your schemes make the coach lvl based so the higher the level the higher the boost they give and the make hiring phase like recruiting

Already considering this in a future release!

> Add receiving year to running backs

Already considering this in a future release!

> Fix all league teams my 3 receivers will put 150+ rectpion 2000+ yards and 30+ tds and not make the team but a receiver with 750 yards and 8 tds will

Check if your receivers have a high number of drops and fumbles -- if they do, then their vote totals for these awards will take a massive hit. However, receivers with that few yards and TDs shouldn't be nominated to those teams. If you do see those, please let me know by filing a bug. 

> Fix defenses where DL should get more sacks than the like back in 4-3 defense

Eh, this is how the game is already written, but if you have an LB that's much higher rated than any of your DLs, then they're just going to end up getting more sacks based on that. I don't think this is a massive issue.
