### ISSUE TITLE
Recruit filtering

### ISSUE THREAD

**Issue by 22goforit** [akeaswaran/cfc-bugs#45]
**Is your feature request related to a problem? Please describe.**
If my coach runs a certain offense or defense, then I’m looking for particular players. It’s frustrating to scroll through hundreds of players when I’m only looking for a dozen in that group. 

**Describe the solution you'd like**
A filtering feature that would show me only players that match a particular criteria. The filtering categories would be player subtype, potential, home state. Maybe even filtering by different player characteristics. For example with a QB, filtering by throwing accuracy, throwing power, injury risk, scrambling ability.

**Comment by akeaswaran** [comment]
This will be added in the next release. Thanks for suggesting this!
