### ISSUE TITLE
Names and conferences 

### ISSUE THREAD

**Issue by Kennan2002** [akeaswaran/cfc-bugs#46]
Can u make an option on the home screen to edit conferences team names and their prestige kinda like The rebrand program feature but for all teams 

And have two slots to choose from the home screen: current one already in place and the custom one

**Comment by akeaswaran** [comment]
You can already edit team names at the end of each season. Head to a team's profile page and tap the edit button at the top right of the screen (it looks like a pad and pencil). You can update conference names and abbreviations from the Settings panel.
