### ISSUE TITLE
Depth Chart

### ISSUE THREAD

**Issue by calebqueen** [akeaswaran/cfc-bugs#48]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by calebqueen** [comment]
There are certain things in this game that do bug me, the biggest one being the prestige system. I dunno about y’all, but it frustrates me when my team has 32 prestige and we go 7-5 but don’t go up in prestige because they projected us to go 7-5. I should go up in prestige because I outperformed the play of a team that has 32 prestige.

**Comment by calebqueen** [comment]
And for another thing, I do want to see running backs get receiving stats because that’s such a big part of the position.

**Comment by akeaswaran** [comment]
Running back receiving stats will be in 4.2, along with an update to the prestige system. Thanks for suggesting these!
