### ISSUE TITLE
Some Little Changes 

### ISSUE THREAD

**Issue by Zixire** [akeaswaran/cfc-bugs#50]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**
I’d like to be able to change my players names and for there to also be numbers that use users can assign to them. Another request I have is being able to get points back during recruiting, only if that player had strong interest in the program. Lastly I think players that are 4-5 star shouldn’t come into the program as high 60’s or low 70’s. 

**Additional context**

**Comment by akeaswaran** [comment]
> I’d like to be able to change my players names and for there to also be numbers that use users can assign to them. 

I'm considering this for a future release!

> Another request I have is being able to get points back during recruiting, only if that player had strong interest in the program.

I'm not sure I understand this request, but in any case, I don't foresee this happening. IRL, programs don't get back expended effort on the recruiting trail, and the game mimics that. 

> Lastly I think players that are 4-5 star shouldn’t come into the program as high 60’s or low 70’s.

Ehhh, I'm not so sure this is a big deal. Part of the risk of recruiting players is that they may not pan out _or_ they may be worse than expected. An overall rating in the low 70s as a recruit is pretty good, and any recruit at that level probably has a high potential rating to boot, meaning that they'll end up being a very good player. TL;DR: I think this is fine as-is.

Thanks for the feedback!
