### ISSUE TITLE
Positions 

### ISSUE THREAD

**Issue by Zixire** [akeaswaran/cfc-bugs#51]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
I think that we should be able to change player’s positions, especially if there not playing. In college this happens often.

**Comment by akeaswaran** [comment]
Positional changes are not happening, unfortunately. More details on this design decision [here](https://www.reddit.com/r/FootballCoach/comments/hr78nb/feature_request/). Thank you for the suggestion, though!
