### ISSUE TITLE
New Feature 

### ISSUE THREAD

**Issue by AcidicWayne** [akeaswaran/cfc-bugs#56]
**Is your feature request related to a problem? Please describe.**
No.
**Describe the solution you'd like**

**Describe alternatives you've considered**
A feature that allows you to make your players stay all 4 years as opposed to leaving early, just a setting you can turn on or off for easier difficulty.
**Additional context**

**Comment by akeaswaran** [comment]
Eh, players leaving early happens at such a low rate already that I don't think this is necessary. Removing that mechanic from the game also moves the world of the game farther from reality, which goes against a central design principle (#2 [here](https://www.reddit.com/r/FootballCoach/comments/cgkyna/cfc_40_update/?utm_source=reddit&utm_medium=usertext&utm_name=FootballCoach&utm_content=t3_j234tl)). Given these two things, I don't think I will be pursuing this; sorry. Thank you for the feedback, though!
