### ISSUE TITLE
Trick Plays

### ISSUE THREAD

**Issue by tyrpar** [akeaswaran/cfc-bugs#59]
I think it would be cool if there were plays such as reverses or flea flicker. It would be a fun way to use your WRs speed in action.

**Comment by akeaswaran** [comment]
WRs don't have rushing stats (nor will they -- I'm wary of adding more complexity to the simulation engine), so jet sweeps and reverses kinda don't make sense in the simplified world of the game. If this is something the community really wants to see, I can build it out, but at this time, I don't think it's high on the list of priority requests. Thanks for the suggestion, though!
