### ISSUE TITLE
Please fill out the template so that I can help you most effectively.

### ISSUE THREAD

**Issue by teryakibeef** [akeaswaran/cfc-bugs#6]
**Describe the bug**

**To Reproduce**

**iOS version**: Version of iOS this bug occurred on (can be found in Settings.app > General)
**CFC version**: Version of CFC this bug occurred on (can be found in CFC's My Team/Career tab > Gear icon > scroll to the bottom)
**iOS device**: For example iPhone XS, iPad mini, etc.
**Jailbroken**: Whether or not your device is jailbroken
**Reproducible:** Can you reproduce it every time? Or is it random?

**Expected behavior**

**Screenshots**
If possible, add screenshots to help show the problem.

**Video**
If possible, attach a video to help show the problem. You can attach a video by uploading it to Streamable, Gfycat, YouTube, etc. and pasting the URL here.

**Additional context**

**Comment by teryakibeef** [comment]
I have the rush shield o-line and it shows that i dont get the bonuses for the smash mouth offense

**Comment by akeaswaran** [comment]
This will be fixed in 4.0.4. Thank you for reporting this, but please fill out the template next time.
