### ISSUE TITLE
Receiving stats for running backs

### ISSUE THREAD

**Issue by JCM1728** [akeaswaran/cfc-bugs#60]
**Is your feature request related to a problem? Please describe.**

•Not necessarily a problem, just a feature I think would make the game a bit better. 

**Describe the solution you'd like**

•Just add the ability for running backs to be targeted in the pass game, and keep up with their receiving stats. Have them count towards POTY voting too. 

**Describe alternatives you've considered**

**Additional context**

**Comment by akeaswaran** [comment]
Closing -- replied to your Reddit thread, but this is slated for the 4.2 release!
