### ISSUE TITLE
Can’t recruit in 2026

### ISSUE THREAD

**Issue by shobekade** [akeaswaran/cfc-bugs#62]
It won’t let me go to recruiting after 2026 season. Since i can’t do that, i can’t continue past the 2026 season

**Comment by akeaswaran** [comment]
Please fill out the template next time.

This was a bug in 4.2 that occurred when your head coach's contract expired. It should be fixed in 4.2.1, but that is still waiting for review. Once that update is out, please let me know if you are still experiencing this issue.
