### ISSUE TITLE
won’t let me recruit after the season ends

### ISSUE THREAD

**Issue by jordanfields** [akeaswaran/cfc-bugs#63]
Please fill out the template below to make sure I can assist you most effectively.

**Describe the bug**

**To Reproduce**

**iOS version**: Version of iOS this bug occurred on (can be found in Settings.app > General)
**CFC version**: Version of CFC this bug occurred on (can be found in CFC's My Team/Career tab > Gear icon > scroll to the bottom)
**iOS device**: For example iPhone XS, iPad mini, etc.
**Jailbroken**: Whether or not your device is jailbroken
**Reproducible:** Can you reproduce it every time? Or is it random?

**Expected behavior**

**Screenshots**
If possible, add screenshots to help show the problem.

**Video**
If possible, attach a video to help show the problem. You can attach a video by uploading it to Streamable, Gfycat, YouTube, etc. and pasting the URL here.

**Additional context**

**Comment by akeaswaran** [comment]
Next time, please fill out the template.

This issue was caused by a bug in 4.2 that affected handling of expiring head coach contracts. This has been patched in 4.2.1, now available on the App Store.
