### ISSUE TITLE
No issues at all!

### ISSUE THREAD

**Issue by Gmanguy** [akeaswaran/cfc-bugs#64]
I love this game so much! I just wish that the players had more of a life like feel. This game is awesome but because the players are just names it losses the lifelike feel. If they had a moral system/chemistry system that would be really cool. Also if they could have personality scores and if they had really bad scores they might get suspended or something like that. One last thing, I think that more options for gameplay would be good. If you could put in like having less minutes in a game because I try to play most of the games but they take so long to get through. 
Thank you for the great game!

**Comment by akeaswaran** [comment]
Thanks for the suggestion! I'll consider this for inclusion in a future release (note: this is not a promise that it will appear in the game, only that I will consider it).
