### ISSUE TITLE
Please provide a descriptive title here, then fill out the rest of the template.

### ISSUE THREAD

**Issue by tharness8806** [akeaswaran/cfc-bugs#66]
Please fill out the template below to make sure I can assist you most effectively.

Unable to hire HC in school mode once current HC is fired 

**To Reproduce**
Upon starting school mode I simulated the first season and then fired the entire coaching staff. When trying to hire my own staff I could hire OC and DC but when I hired a HC it said I had hired him but the system did not recognize it. I tried multiple times hiring OCs DCs and other HCs to try to fill the position but it would keep saying I needed to hire a new HC 

**iOS version**: Version of iOS this bug occurred on (can be found in Settings.app > General)
**CFC version**: Version of CFC this bug occurred on (can be found in CFC's My Team/Career tab > Gear icon > scroll to the bottom)
**iOS device**: For example iPhone XS, iPad mini, etc.
**Jailbroken**: Whether or not your device is jailbroken
**Reproducible:** Can you reproduce it every time? Or is it random?

**Expected behavior**

**Screenshots**
If possible, add screenshots to help show the problem.

**Video**
If possible, attach a video to help show the problem. You can attach a video by uploading it to Streamable, Gfycat, YouTube, etc. and pasting the URL here.

**Additional context**

**Comment by akeaswaran** [comment]
This is a bug in the current implementation of hiring head coaches. If you choose a coordinator to use as your head coach, they will be added to your staff as a coordinator instead of the head coach. I've patched this in the next update (4.2.2), but for now, you can get around this by hiring head coaches to fill the head coach slot.
