### ISSUE TITLE
Off-season hiring a head coach bug

### ISSUE THREAD

**Issue by Quise1k** [akeaswaran/cfc-bugs#67]
Please fill out the template below to make sure I can assist you most effectively.

**Describe the bug**

When it was the offseason it told my to hire a new head coach but my current head coach contract had not expire and when I did go hire Ia new one it still Said the same thing even when I fired my head Coach and got a new one  it still did it This is the second time

**To Reproduce**

1.Head coach on his last year of his contract
2. Try to hire a new one
3. See error
4. Then it will Say file corrupt

The pictures are in  @order
![2519A695-AC1A-450A-9E67-060D0E18256D](https://user-images.githubusercontent.com/73563530/97374376-84f4f200-188e-11eb-8404-2ca288646c01.png)
![9153B6D6-A5F8-4846-9ADF-2696D006E9F1](https://user-images.githubusercontent.com/73563530/97374383-87574c00-188e-11eb-81f8-5677bd259c69.png)
![429694DC-237F-41D8-9E5C-9AA56840C0C4](https://user-images.githubusercontent.com/73563530/97374385-87efe280-188e-11eb-94d9-2108d97f324e.png)
![007680D3-481A-45C2-90F2-5B5ED647B8C1](https://user-images.githubusercontent.com/73563530/97374386-88887900-188e-11eb-9cc1-b679ab006320.png)

**iOS version**: Version of iOS this bug occurred on (can be found in Settings.app > General)
**CFC version**: Version of CFC this bug occurred on (can be found in CFC's My Team/Career tab > Gear icon > scroll to the bottom)
**iOS device**: For example iPhone XS, iPad mini, etc.
**Jailbroken**: Whether or not your device is jailbroken
**Reproducible:** Can you reproduce it every time? Or is it random?

**Expected behavior**

**Screenshots**
If possible, add screenshots to help show the problem.

**Video**
If possible, attach a video to help show the problem. You can attach a video by uploading it to Streamable, Gfycat, YouTube, etc. and pasting the URL here.

**Additional context**

**Comment by akeaswaran** [comment]
Thanks for letting me know about this and leaving a detailed bug report. I think I have patched this in 4.2.2. If you're still experiencing this bug when that rolls out, please reopen this issue. Thanks for your help!
