### ISSUE TITLE
Punters, ability to play backups and fire OC DC options and possibly adding switching conference features

### ISSUE THREAD

**Issue by camgroves13** [akeaswaran/cfc-bugs#68]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by akeaswaran** [comment]
Conference switching is partially supported by pro/rel in 4.2.x. I may build on this further, but I like where I'm at with that right now.

Punters are not really necessary to the game -- it's just another type of kick. 

Subs will not be coming to the game. See #58.
