### ISSUE TITLE
Retirement 

### ISSUE THREAD

**Issue by DustyPd** [akeaswaran/cfc-bugs#69]
Just wanted to see if a retirement option was in the works.

Also, what are your thoughts about having an option to be a coordinator?

**Comment by akeaswaran** [comment]
There's always been a retirement option for coaches in Career Mode -- the coach has to reach age 60 (or 65 -- I don't remember offhand) before that option appears.

I'm not planning on supporting a coordinator mode at this time. However, if there's enough interest for that in our community (like on [/r/FootballCoach](https://reddit.com/r/FootballCoach), then I can explore building it out.
