### ISSUE TITLE
Team History entries are misassigned

### ISSUE THREAD

**Issue by slamdunkjones** [akeaswaran/cfc-bugs#7]
Please fill out the template below to make sure I can assist you most effectively.

**Describe the bug**

When you join a new team the team history attributes their last season to you, and your last season with your previous team is given to their new coach

**To Reproduce**

**iOS version**: Version of iOS this bug occurred on (can be found in Settings.app > General)
**CFC version**: Version of CFC this bug occurred on (can be found in CFC's My Team/Career tab > Gear icon > scroll to the bottom)
**iOS device**: For example iPhone XS, iPad mini, etc.
**Jailbroken**: Whether or not your device is jailbroken
**Reproducible:** Can you reproduce it every time? Or is it random?

**Expected behavior**

**Screenshots**
If possible, add screenshots to help show the problem.

**Video**
If possible, attach a video to help show the problem. You can attach a video by uploading it to Streamable, Gfycat, YouTube, etc. and pasting the URL here.

**Additional context**

**Comment by akeaswaran** [comment]
Should be fixed in the 4.1 beta.
