### ISSUE TITLE
Coaching tree? The ability to see where assistants go after their contracts expire and stats tabs that show all the players 

### ISSUE THREAD

**Issue by camgroves13** [akeaswaran/cfc-bugs#73]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by akeaswaran** [comment]
Great idea, but this would result in saving a lot more data. I'll keep this ticket open and under consideration, but I don't see it coming to the game in the near future. Thanks for the suggestion, though!
