### ISSUE TITLE
A few features i think would be nice ? 

### ISSUE THREAD

**Issue by spencerfootball** [akeaswaran/cfc-bugs#74]
Hi Thanks for making this game it’s been fun playing for the past year :) anyways i was wondering if you could add a view coaching staff option would be little bit useful ! also is there a way for you to add some sort of manual training like for exp: before a game there could be a practice or training tab where i could make my players focus on a certain thing or make there training boosted in some sort of way. 

-spencer

**Comment by akeaswaran** [comment]
Training sessions are something I'm interested in exploring in a future release (note: this does not guarantee that they will actually make it into the game, nor does it guarantee any sort of timeline for inclusion).

I'm not sure what you mean by "view coaching staff" option -- you can view all coaches on a team by viewing the team's profile page.
