### ISSUE TITLE
Coordinator Contracts

### ISSUE THREAD

**Issue by palmerellis** [akeaswaran/cfc-bugs#77]
**Describe the bug**

When I extend coordinator contracts the time left on the contracts extends to the contract length minus one year.

Example - I extended my offensive coordinator contract for the third time by four years in my fifth year. His contract should be 12 years with 7 years left, but shows as 12 years with 11 years left. 

Not a big deal and is even kinda handy because I don’t have to come back as often to extend his contract, but thought you might want to know. This game is awesome, and all the changes over the years have been awesome. I downloaded this game back in 2016 and have been playing ever since. You have done a great job changing the app to make the game change. I am a really big fan. 

**To Reproduce**
The behavior happens for me in easy career mode. 
Career> current team> off coordinator> •••> extend contract 

**iOS version**: 14.2

**CFC version**: 4.2.5

**iOS device**: IPhone7

**Jailbroken**: No

**Reproducible**: not sure

**Screenshots**
If possible, add screenshots to help show the problem.

I have screen shots of my off coordinators contract getting extended, from 30 years (28 left) to 63 (62 left). This was one four year extension. Not sure how to upload the pictures. I have only extend his contract a total of like 4 times

**Comment by akeaswaran** [comment]
Thanks for letting me know about this! Looks like this was a pretty simple fix, so I'll add this to a future update.
