### ISSUE TITLE
Playoffs Option 

### ISSUE THREAD

**Issue by palmerellis** [akeaswaran/cfc-bugs#78]
**Is your feature request related to a problem? Please describe.**
No problem

**Describe the solution you'd like**
I would love to see expanded playoff system. I know that this is based on the current college playoff model, but I think it would be awesome to add an option for the number of playoff teams. Also I think that the option of each conference getting their conference champion in the playoff would be good. 

Personally I like the idea of making the playoffs options 4, 8, 12 (4 teams with byes), 16, 28 (4 teams with byes)

**Comment by akeaswaran** [comment]
Duplicate of #35 -- see that issue for more details.
