### ISSUE TITLE
I was wondering if there was a way to put the OL in the awards too so they can get into the RING of honor/ HOF and can there be defensive and special teams TDs I have gotten any so far? And what defense in your opinion creates the most sacks on here??

### ISSUE THREAD

**Issue by camgroves13** [akeaswaran/cfc-bugs#79]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by akeaswaran** [comment]
> put the OL in the awards too so they can get into the RING of honor/ HOF

The game does not record stats for individual OLs, so there's no data that can be used to score their careers and put them in the HoF/RoH. The question you might ask here is: "Why aren't there?" -- the game considers the OL as a unit and doesn't assign blame for sacks or pressures to a specific OL.

> can there be defensive and special teams TDs

There are no special teams TDs in the game. There is one class of defensive TD (when a fumble is recovered in the end zone), but those are incredibly rare. There haven't been a lot of requests for these, so I haven't prioritized adding them.

> And what defense in your opinion creates the most sacks on here??

It depends on your personnel -- I suggest you read through the bonuses and penalties each defensive playbook provides and pick one that best boosts the players on your roster.
