### ISSUE TITLE
No job offers after importing custom league metadata

### ISSUE THREAD

**Issue by dylan-bowman** [akeaswaran/cfc-bugs#8]
Please fill out the template below to make sure I can assist you most effectively.

**Describe the bug**
No job offers after importing custom league metadata. No jobs available on the coaching carousel. Tried three seasons over two different saves.

**To Reproduce**
Start a season using Import custom league metadata. Sim the season. Look for available jobs. None available.

**iOS version**: Version of iOS this bug occurred on (can be found in Settings.app > General)
**CFC version**: Version of CFC this bug occurred on (can be found in CFC's My Team/Career tab > Gear icon > scroll to the bottom)
**iOS device**: For example iPhone XS, iPad mini, etc.
**Jailbroken**: Whether or not your device is jailbroken
**Reproducible:** Can you reproduce it every time? Or is it random?

**Expected behavior**

**Screenshots**
If possible, add screenshots to help show the problem.

**Video**
If possible, attach a video to help show the problem. You can attach a video by uploading it to Streamable, Gfycat, YouTube, etc. and pasting the URL here.

**Additional context**

**Comment by akeaswaran** [comment]
This doesn't sound like an in-game issue. If the metadata file has been edited such that each coach has a contractYear value less than their contractLength value and a cumulativePrestige value that's not negative, they'll all be employed for a few years before they hit negative cumulative prestige values and get fired. Three seasons does seem like enough to trigger some firings, but again, it does depend on the metadata file. If you can link me to the one you're using, I can check it out.
