### ISSUE TITLE
The stats for players during the recruiting period needs to be more random. The reason is because when I look one players stats and see his stats I look at 4 other people and they also have the same stats so I’m asking y’all to make the stats more random

### ISSUE THREAD

**Issue by eli2626** [akeaswaran/cfc-bugs#83]
Please fill out the template below to make sure I can assist you most effectively.

**Describe the bug**

**To Reproduce**

**iOS version**: Version of iOS this bug occurred on (can be found in Settings.app > General)
**CFC version**: Version of CFC this bug occurred on (can be found in CFC's My Team/Career tab > Gear icon > scroll to the bottom)
**iOS device**: For example iPhone XS, iPad mini, etc.
**Jailbroken**: Whether or not your device is jailbroken
**Reproducible:** Can you reproduce it every time? Or is it random?

**Expected behavior**

**Screenshots**
If possible, add screenshots to help show the problem.

**Video**
If possible, attach a video to help show the problem. You can attach a video by uploading it to Streamable, Gfycat, YouTube, etc. and pasting the URL here.

**Additional context**

**Comment by akeaswaran** [comment]
This is slated to be fixed in a future release. Thanks for letting me know about this!
