### ISSUE TITLE
Great App! Some great feature suggestions from a fan of your apps

### ISSUE THREAD

**Issue by UnlimitedSportsIncGaming** [akeaswaran/cfc-bugs#88]
- Being able to add a few more bowl games and have a symbol next to the name
- A pro football coach updated version of this app to bring over draft classes and play with teams who have your old players, apply to draft awesome players from CFC, etc
- I believe a College and Pro Basketball Version of this app would be hugely successful! I’d definitely play it!

Good chatting with you! You can contact me @usigaming on IG and Unlimited Sports Inc Gaming on Facebook, My email is lawrencegoggans@yahoo.com

**Comment by akeaswaran** [comment]
Thanks for the feedback! Let me respond to each of your points separately:

> Being able to add a few more bowl games and have a symbol next to the name

The number of bowl games is fixed based on the average number of six-win teams in the game in a season -- changes to this will not be coming, unfortunately.

> A pro football coach updated version of this app to bring over draft classes and play with teams who have your old players, apply to draft awesome players from CFC, etc
> I believe a College and Pro Basketball Version of this app would be hugely successful! I’d definitely play it!

I do not have plan to develop pro football and basketball versions of this game. I'm focused on the game that exists and making sure that it's the best it can be! More details on pro football specifically [here](https://reddit.com/r/FootballCoach/comments/ga4ol0/_/fp158y5/?context=1).
