### ISSUE TITLE
Cpu recruiting

### ISSUE THREAD

**Issue by dtill2** [akeaswaran/cfc-bugs#89]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

When you control a school and let the cpu hire and fire coaches it would be cool to add a recruiting number to the coach and let the coach/cpu recruit to give it better feel as you as an AD and let the coach recruit what he wants

**Comment by akeaswaran** [comment]
Thanks for suggesting this! I'll consider adding this in a future release (note: this is not a promise that it will appear in the game; only that I'm considering it).
