### ISSUE TITLE
Bruh

### ISSUE THREAD

**Issue by teryakibeef** [akeaswaran/cfc-bugs#9]
You should add a starting tight end to the west coast or spread play book because tight ends are useless if you use those play books

**Comment by akeaswaran** [comment]
Well, yeah -- some offensive schemes in real life don't use TEs or an extra RB either. Having different positional availability in different playbooks gives users the opportunity to play their way, and those ways are meant to simulate real-life offenses and scheming. For example, if you want to play some games with 4-wide sets against bad pass defenses, you can choose the Spread; if you want to bring out the jumbo package against a team that's bad at stopping the run, you can use the Smashmouth playbook to add an extra RB and a blocking TE. I don't feel that this design choice is an issue, but I'm open to a discussion on it.
