### ISSUE TITLE
Height and Weight listing for the players

### ISSUE THREAD

**Issue by UnlimitedSportsIncGaming** [akeaswaran/cfc-bugs#92]
The players height and weight listing was a cool feature for me and as a fan of this game I’d like to see it again. I usually take my best players from this app and create them on the NCAA Football game bringing them to somewhat real life! It’s really cool.

**Comment by akeaswaran** [comment]
Thanks for the feedback! These stats were never supposed to be removed -- they'll be back in a future release.

**Comment by UnlimitedSportsIncGaming** [comment]
Thank you I really appreciate your efforts!


Sent from Yahoo Mail for iPhone


On Saturday, December 19, 2020, 1:02 PM, Akshay Easwaran <notifications@github.com> wrote:




Thanks for the feedback! These stats were never supposed to be removed -- they'll be back in a future release.
