### ISSUE TITLE
Dividing conferences 

### ISSUE THREAD

**Issue by axeman2077** [akeaswaran/cfc-bugs#93]
I had an idea that you could split conferences up like in real life, like the B1G east and west. Just an idea, have a good Christmas .

**Comment by akeaswaran** [comment]
Thanks for the feedback! Unfortunately, I'm not looking at adding divisions to the game. Supporting the various ways that division scheduling can be conducted would greatly overcomplicate the simulation engine, and that's not work I want to do unless there's a lot of interest from the community for it.
