### ISSUE TITLE
NCG Crash Issue

### ISSUE THREAD

**Issue by stevandj8** [akeaswaran/cfc-bugs#94]
Please fill out the template below to make sure I can assist you most effectively.

**Describe the bug**
I am a few seasons into a career with Alabama in the game, but I am stuck on the NCG game. Whenever I try to sim through it or play it myself, the whole app crashes. There seems to be no way to get around it.

**To Reproduce**
I believe this is more of a case-specific issue than something that can be reproduced.

**iOS version**: Version of iOS this bug occurred 
13.3

**CFC version**: Version of CFC this bug
newest version (app was just downloaded)

**iOS device**: For example iPhone XS, iPad mini, etc.
iPhone XR

**Jailbroken**: Whether or not your device is jailbroken
no

**Reproducible:** Can you reproduce it every time? Or is it random?
Random?

**Expected behavior**
I expected the NCG to work and to be able to continue with my career mode save.

**Screenshots**
If possible, add screenshots to help show the problem.

**Video**
If possible, attach a video to help show the problem. You can attach a video by uploading it to Streamable, Gfycat, YouTube, etc. and pasting the URL here.

**Additional context**

**Comment by akeaswaran** [comment]
Thanks for reporting this! Unfortunately, this isn't a lot to go off to diagnose the problem. I haven't seen anything occurring around NCG week in my crash reporter so I'm not sure what other support I can provide. My recommendation would be to start a fresh save file if possible. Sorry that I can't be of more help.
