### ISSUE TITLE
Undefeated big ten champ ranked 7th at end of season.

### ISSUE THREAD

**Issue by buckeye9317** [akeaswaran/cfc-bugs#96]
![CADD433A-7673-4287-A946-A028778E1225](https://user-images.githubusercontent.com/76663218/103178602-4493ff00-4852-11eb-84c9-b3b3be93181a.png)
![C3A97326-5716-4171-8CFD-03957E4D1C0E](https://user-images.githubusercontent.com/76663218/103178603-465dc280-4852-11eb-8c20-84611a13da53.png)
![32FBA1CD-E0DD-482B-851A-AA76CBD04D32](https://user-images.githubusercontent.com/76663218/103178604-48278600-4852-11eb-9466-9de4be45b06d.png)
![AB36D880-65BE-42F5-9B68-B847282E0EC1](https://user-images.githubusercontent.com/76663218/103178607-4958b300-4852-11eb-8ea1-6693abb4a702.png)
![BD3564B3-14AB-47C2-B593-600E4C953110](https://user-images.githubusercontent.com/76663218/103178609-49f14980-4852-11eb-86cf-c9444a72257d.png)
![A6E83E0E-B504-4559-AD10-369FF7AB8B59](https://user-images.githubusercontent.com/76663218/103178610-4b227680-4852-11eb-8f8a-2acee7ceecde.png)
![F60638E9-FDBB-45B2-B5AE-44D93970F63A](https://user-images.githubusercontent.com/76663218/103178612-4c53a380-4852-11eb-984d-658aa7277d50.png)
![229824CC-0223-4435-AA02-5F226C0D9FD4](https://user-images.githubusercontent.com/76663218/103178614-4d84d080-4852-11eb-98ad-aa6a5f11d6ca.png)
![3E889FB9-2B57-4ACD-BC01-DE919D0FCC7E](https://user-images.githubusercontent.com/76663218/103178617-4f4e9400-4852-11eb-8287-400bacb15018.png)
![D8225C5C-E905-47E5-BE03-54632E91C7F9](https://user-images.githubusercontent.com/76663218/103178619-507fc100-4852-11eb-911f-6ee5b7c03b97.png)

**Comment by akeaswaran** [comment]
Not a bug -- all of those teams ranked #1-6 had better-ranked strengths of schedule, as your screenshots show.

**Comment by buckeye9317** [comment]
5 or so teams being undefeated would never happen in real life. Especially a team coming off multiple championships.
