### ISSUE TITLE
Please provide a descriptive title here, then fill out the rest of the template.

### ISSUE THREAD

**Issue by pfightingirish** [akeaswaran/cfc-bugs#97]
Please fill out the template below to make sure I can assist you most effectively.

**Describe the bug**
When you win a national championship, the coaches security just moved up to “ok”. I would think that the year after winning a national championship, the coach should be very secure in their job, but it isn’t.

**To Reproduce**

**iOS version**: Version of iOS this bug occurred on (can be found in Settings.app > General)
**CFC version**: Version of CFC this bug occurred on (can be found in CFC's My Team/Career tab > Gear icon > scroll to the bottom)
**iOS device**: For example iPhone XS, iPad mini, etc.
**Jailbroken**: Whether or not your device is jailbroken
**Reproducible:** Can you reproduce it every time? Or is it random?

**Expected behavior**

**Screenshots**
If possible, add screenshots to help show the problem.
![6A7EDC2F-5D21-4127-993D-390449620454](https://user-images.githubusercontent.com/76876222/103460907-33cb0980-4ce8-11eb-8248-d49173eaf8ec.png)

**Video**
If possible, attach a video to help show the problem. You can attach a video by uploading it to Streamable, Gfycat, YouTube, etc. and pasting the URL here.

**Additional context**

**Comment by akeaswaran** [comment]
Your job status is dependent on your cumulative prestige, which is the number of prestige points you have gained/lost from your baseline prestige. Your cumulative prestige is 0, which effectively means that the program is in the same position as it was when you started there. Thus, your job status is merely ok.
