### ISSUE TITLE
Draftees

### ISSUE THREAD

**Issue by RichPimp** [akeaswaran/cfc-bugs#99]
I think it would be nice to be able to track your players that get drafted and see how their careers go. There’s this basketball game that does it pretty good
![2C7E8202-D7DC-4EAC-BBCC-94680032E3C7](https://user-images.githubusercontent.com/76967487/103567618-218ccf00-4e92-11eb-962b-628f93133ddf.png)

**Comment by akeaswaran** [comment]
You can see where/when members of a program's ring of honor were drafted, but I do not plan on supporting pro career/stats generation for drafted players in the near future.
